package define

const (
	InitialRoleLv int32 = iota + 1
	InitialRoleExp
	RoleLvMax
	InitialMagicKingLv
	MagicKingLvMax
	InitialSoldierLv
	InitialSoldierExp
	SoldierLvMax
	InitialSoldierSkillLv
	SoldierSkillLvMax
	SoldierTypeNum
	InitialHeroLv
	InitialHeroExp
	HeroLvMax
	InitialHeroSkillLv
	HeroSkillLvMax
	HeroTypeNum
	HeroNumLimit
	HeroRankLimit
	InitialBuildingLv
	BuildingLvMax
	BuildingTypeNum
	CancelBuildingReturn
	InitialMagicKingSkillLv
	MagicKingSkillLvMax
	MagicKingSkillTypeNum
	CancelMagicKingSkillReturn
	InitialBlood
	InitialSoul
	InitialGold
	InitialTrophy
	InitialShield
	InitialOrder
	InitialSpirit
	OrderRecover
	SpiritRecover
	InitialMix
	MixRecover
	MixNumMin
	MixNumMax
	InitialOrderBuyNum
	InitialSpiritBuyNum
	BuyNumRefreshClock
	InitialItem
	InitialSoldier
	StageNum
	OrdinaryStageSweepNum
	EliteStageSweepNum
	FbNum
	BattleReadyTime
	BattleTime
	BattleDefenseAttackPlus
	BattleDefenseSpeedPlus
	InitialBattleHeroEnergy
	BattleHeroEnergyMax
	HeroEnergyRecover1
	HeroEnergyRecover2
	HeroEnergyRecover3
	HeroEnergyRecover4
	HeroEnergyRecover5
	MagicKingEnergyRecover1
	MagicKingEnergyRecover2
	MagicKingEnergyRecover3
	LeagueResetInterval
	LeagueOwnPlayerNum
	LeagueTopPlayerNum
	InitialLeagueLv
	InitialLeagueVictoryNum
	InitialLeagueFailureNum
	ChatWordsLimit
	ChatInterval
	ChatWorldShowNum
	ChatPrivateShowNum
	InitialChatFreeTime
	ChatFreeTimeRefreshClock
	ChatNeedGold
	FriendNumLimit
	FriendGiveAward
	FriendReceiveTime
	FriendRefreshClock
	InitialFriendVictoryNum
	InitialFriendFailureNum
	BattleReportDefenseNum
	BattleReportAttackNum
	BattleVideoLifeCycle
	BattleVideoShareInterval
	AchievementNum
	DailyTaskNum
	DailyTaskRefreshClock
	InitialSign
	SignResetInterval
	SignRefreshClock
	InitialPayLv
	InitialPayExp
	PayLvMax
	InitialVipQualification
	MagicHeroCreateCD
	DrawOneNeedGold
	DrawTenNeedGold
	OffLineTime
	FeedingEvent1IntervalMin
	FeedingEvent1IntervalMax
	FeedingEvent1Duration
	FeedingEvent2IntervalMin
	FeedingEvent2IntervalMax
	FeedingEvent2Duration
	FeedingEvent3IntervalMin
	FeedingEvent3IntervalMax
	FeedingEvent3Duration
	TimeParam1
	TimeParam2
	TimeParam3
	TimeParam4
	TimePrice1
	TimePrice2
	TimePrice3
	TimePrice4
	BloodParam1
	BloodParam2
	BloodParam3
	BloodParam4
	BloodPrice1
	BloodPrice2
	BloodPrice3
	BloodPrice4
	SoulParam1
	SoulParam2
	SoulParam3
	SoulParam4
	SoulPrice1
	SoulPrice2
	SoulPrice3
	SoulPrice4
	ModifyNickname
	EvoSpeedRecover
	EvoSpeedValue
	MagicHeroCreateShockGold
	MagicHeroCreateShockLife
	InitialMagicHeroCreateLife
	Event1TimeDown
	Event1TimeUp
	Event1CorpseLimit
	Event1Duration
	Event2TimeDown
	Event2TimeUp
	Event2Award1
	Event2Award2
	Event2Award3
	Event2Award4
	Event2Award5
	Event2Award1Param
	Event2Award2Param
	Event2Award3Param
	Event2Award4Param
	Event2Award5Param
	Event2Duration
	Event3TimeDown
	Event3TimeUp
	Event3Weaken
	Event3HelpRefreshClock
	OutputPlunderParam
	BloodDepositPlunderParam1
	BloodDepositPlunderParam2
	BloodDepositPlunderParam3
	BloodDepositPlunderParam4
	BloodDepositPlunderParam5
	BloodDepositPlunderParam6
	BloodCanPlunderParam1
	BloodCanPlunderParam2
	BloodCanPlunderParam3
	BloodCanPlunderParam4
	BloodCanPlunderParam5
	BloodCanPlunderParam6
	SoulDepositPlunderParam1
	SoulDepositPlunderParam2
	SoulDepositPlunderParam3
	SoulDepositPlunderParam4
	SoulDepositPlunderParam5
	SoulDepositPlunderParam6
	SoulCanPlunderParam1
	SoulCanPlunderParam2
	SoulCanPlunderParam3
	SoulCanPlunderParam4
	SoulCanPlunderParam5
	SoulCanPlunderParam6
	ResourcesProtectParam1
	ResourcesProtectParam2
	ResourcesProtectParam3
	ResourcesProtectParam4
	ResourcesProtectParam5
	ResourcesProtectParam6
	ResourcesProtectParam7
	ResourcesProtectParam8
	ResourcesProtectParam9
	ResourcesProtectParam10
	ResourcesProtectParam11
	TrophyMatching
	TrophyProtectLine
	TrophyProtectParam
	LineDownTrophyVictoryParam1
	LineDownTrophyVictoryParam2
	LineDownTrophyFailureParam1
	LineDownTrophyFailureParam2
	LineUpTrophyVictoryParam1
	LineUpTrophyVictoryParam2
	LineUpTrophyFailureParam1
	LineUpTrophyFailureParam2
	PvpCostSpirit
	PvpVictoryExp
	PvpLeastExp
	TimeNum1
	TimeNum2
	TimeNum3
	TimeNum4
	OrderCost1
	OrderCost2
	OrderCost3
	OrderCost4
	OrderCost5
	SpiritCost1
	SpiritCost2
	SpiritCost3
	SpiritCost4
	SpiritCost5
	ChatQueryLimitT
)
