// Code generated by protoc-gen-go.
// source: activity.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 掠夺类型
type ActivityOpenFlag int32

const (
	ActivityOpenFlag_Off ActivityOpenFlag = 0
	ActivityOpenFlag_On  ActivityOpenFlag = 1
)

var ActivityOpenFlag_name = map[int32]string{
	0: "Off",
	1: "On",
}
var ActivityOpenFlag_value = map[string]int32{
	"Off": 0,
	"On":  1,
}

func (x ActivityOpenFlag) Enum() *ActivityOpenFlag {
	p := new(ActivityOpenFlag)
	*p = x
	return p
}
func (x ActivityOpenFlag) String() string {
	return proto.EnumName(ActivityOpenFlag_name, int32(x))
}
func (x *ActivityOpenFlag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActivityOpenFlag_value, data, "ActivityOpenFlag")
	if err != nil {
		return err
	}
	*x = ActivityOpenFlag(value)
	return nil
}

type ActivityStatusFlag int32

const (
	ActivityStatusFlag_CanGet    ActivityStatusFlag = 1
	ActivityStatusFlag_CanNotGet ActivityStatusFlag = 0
	ActivityStatusFlag_Geted     ActivityStatusFlag = -1
)

var ActivityStatusFlag_name = map[int32]string{
	1:  "CanGet",
	0:  "CanNotGet",
	-1: "Geted",
}
var ActivityStatusFlag_value = map[string]int32{
	"CanGet":    1,
	"CanNotGet": 0,
	"Geted":     -1,
}

func (x ActivityStatusFlag) Enum() *ActivityStatusFlag {
	p := new(ActivityStatusFlag)
	*p = x
	return p
}
func (x ActivityStatusFlag) String() string {
	return proto.EnumName(ActivityStatusFlag_name, int32(x))
}
func (x *ActivityStatusFlag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActivityStatusFlag_value, data, "ActivityStatusFlag")
	if err != nil {
		return err
	}
	*x = ActivityStatusFlag(value)
	return nil
}

type ActivityOpenInfo struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	IsOpen           *int32 `protobuf:"varint,2,req,name=isOpen" json:"isOpen,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivityOpenInfo) Reset()         { *m = ActivityOpenInfo{} }
func (m *ActivityOpenInfo) String() string { return proto.CompactTextString(m) }
func (*ActivityOpenInfo) ProtoMessage()    {}

func (m *ActivityOpenInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ActivityOpenInfo) GetIsOpen() int32 {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return 0
}

func (m *ActivityOpenInfo) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *ActivityOpenInfo) SetIsOpen(value int32) {
	if m != nil {
		if m.IsOpen != nil {
			*m.IsOpen = value
			return
		}
		m.IsOpen = proto.Int32(value)
	}
}

type MsgActivityListReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgActivityListReq) Reset()         { *m = MsgActivityListReq{} }
func (m *MsgActivityListReq) String() string { return proto.CompactTextString(m) }
func (*MsgActivityListReq) ProtoMessage()    {}

type MsgActivityListRet struct {
	Infos            []*ActivityOpenInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgActivityListRet) Reset()         { *m = MsgActivityListRet{} }
func (m *MsgActivityListRet) String() string { return proto.CompactTextString(m) }
func (*MsgActivityListRet) ProtoMessage()    {}

func (m *MsgActivityListRet) GetInfos() []*ActivityOpenInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgActivityListRet) SetInfos(value []*ActivityOpenInfo) {
	if m != nil {
		m.Infos = value
	}
}

type MsgActivityListNotify struct {
	Infos            []*ActivityOpenInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgActivityListNotify) Reset()         { *m = MsgActivityListNotify{} }
func (m *MsgActivityListNotify) String() string { return proto.CompactTextString(m) }
func (*MsgActivityListNotify) ProtoMessage()    {}

func (m *MsgActivityListNotify) GetInfos() []*ActivityOpenInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgActivityListNotify) SetInfos(value []*ActivityOpenInfo) {
	if m != nil {
		m.Infos = value
	}
}

type ActivityBoxInfo struct {
	Index            *int32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Status           *int32 `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	Condition        *int64 `protobuf:"varint,3,req,name=condition" json:"condition,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivityBoxInfo) Reset()         { *m = ActivityBoxInfo{} }
func (m *ActivityBoxInfo) String() string { return proto.CompactTextString(m) }
func (*ActivityBoxInfo) ProtoMessage()    {}

func (m *ActivityBoxInfo) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ActivityBoxInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ActivityBoxInfo) GetCondition() int64 {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return 0
}

func (m *ActivityBoxInfo) SetIndex(value int32) {
	if m != nil {
		if m.Index != nil {
			*m.Index = value
			return
		}
		m.Index = proto.Int32(value)
	}
}

func (m *ActivityBoxInfo) SetStatus(value int32) {
	if m != nil {
		if m.Status != nil {
			*m.Status = value
			return
		}
		m.Status = proto.Int32(value)
	}
}

func (m *ActivityBoxInfo) SetCondition(value int64) {
	if m != nil {
		if m.Condition != nil {
			*m.Condition = value
			return
		}
		m.Condition = proto.Int64(value)
	}
}

type MsgActivityQueryReq struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgActivityQueryReq) Reset()         { *m = MsgActivityQueryReq{} }
func (m *MsgActivityQueryReq) String() string { return proto.CompactTextString(m) }
func (*MsgActivityQueryReq) ProtoMessage()    {}

func (m *MsgActivityQueryReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgActivityQueryReq) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

type MsgActivityQueryRet struct {
	Id               *int32             `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	IntValues        []int32            `protobuf:"varint,2,rep,name=int_values" json:"int_values,omitempty"`
	Infos            []*ActivityBoxInfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MsgActivityQueryRet) Reset()         { *m = MsgActivityQueryRet{} }
func (m *MsgActivityQueryRet) String() string { return proto.CompactTextString(m) }
func (*MsgActivityQueryRet) ProtoMessage()    {}

func (m *MsgActivityQueryRet) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgActivityQueryRet) GetIntValues() []int32 {
	if m != nil {
		return m.IntValues
	}
	return nil
}

func (m *MsgActivityQueryRet) GetInfos() []*ActivityBoxInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgActivityQueryRet) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *MsgActivityQueryRet) SetIntValues(value []int32) {
	if m != nil {
		m.IntValues = value
	}
}

func (m *MsgActivityQueryRet) SetInfos(value []*ActivityBoxInfo) {
	if m != nil {
		m.Infos = value
	}
}

type MsgActivityOperateReq struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Index            *int32 `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgActivityOperateReq) Reset()         { *m = MsgActivityOperateReq{} }
func (m *MsgActivityOperateReq) String() string { return proto.CompactTextString(m) }
func (*MsgActivityOperateReq) ProtoMessage()    {}

func (m *MsgActivityOperateReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgActivityOperateReq) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *MsgActivityOperateReq) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *MsgActivityOperateReq) SetIndex(value int32) {
	if m != nil {
		if m.Index != nil {
			*m.Index = value
			return
		}
		m.Index = proto.Int32(value)
	}
}

type MsgActivityOperateRet struct {
	Retcode          *int32       `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	Id               *int32       `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Infos            []*AwardInfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgActivityOperateRet) Reset()         { *m = MsgActivityOperateRet{} }
func (m *MsgActivityOperateRet) String() string { return proto.CompactTextString(m) }
func (*MsgActivityOperateRet) ProtoMessage()    {}

func (m *MsgActivityOperateRet) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *MsgActivityOperateRet) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgActivityOperateRet) GetInfos() []*AwardInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgActivityOperateRet) SetRetcode(value int32) {
	if m != nil {
		if m.Retcode != nil {
			*m.Retcode = value
			return
		}
		m.Retcode = proto.Int32(value)
	}
}

func (m *MsgActivityOperateRet) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *MsgActivityOperateRet) SetInfos(value []*AwardInfo) {
	if m != nil {
		m.Infos = value
	}
}

type ActivityStatusInfo struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Index            *int32 `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	Status           *int32 `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	Condition        *int64 `protobuf:"varint,4,req,name=condition" json:"condition,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivityStatusInfo) Reset()         { *m = ActivityStatusInfo{} }
func (m *ActivityStatusInfo) String() string { return proto.CompactTextString(m) }
func (*ActivityStatusInfo) ProtoMessage()    {}

func (m *ActivityStatusInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ActivityStatusInfo) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ActivityStatusInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ActivityStatusInfo) GetCondition() int64 {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return 0
}

func (m *ActivityStatusInfo) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *ActivityStatusInfo) SetIndex(value int32) {
	if m != nil {
		if m.Index != nil {
			*m.Index = value
			return
		}
		m.Index = proto.Int32(value)
	}
}

func (m *ActivityStatusInfo) SetStatus(value int32) {
	if m != nil {
		if m.Status != nil {
			*m.Status = value
			return
		}
		m.Status = proto.Int32(value)
	}
}

func (m *ActivityStatusInfo) SetCondition(value int64) {
	if m != nil {
		if m.Condition != nil {
			*m.Condition = value
			return
		}
		m.Condition = proto.Int64(value)
	}
}

type MsgActivityAwardStatusChangeNotify struct {
	Infos            []*ActivityStatusInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *MsgActivityAwardStatusChangeNotify) Reset()         { *m = MsgActivityAwardStatusChangeNotify{} }
func (m *MsgActivityAwardStatusChangeNotify) String() string { return proto.CompactTextString(m) }
func (*MsgActivityAwardStatusChangeNotify) ProtoMessage()    {}

func (m *MsgActivityAwardStatusChangeNotify) GetInfos() []*ActivityStatusInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgActivityAwardStatusChangeNotify) SetInfos(value []*ActivityStatusInfo) {
	if m != nil {
		m.Infos = value
	}
}

type MsgActivityValueStatusChangeNotify struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ValueStatusInfo  *int64 `protobuf:"varint,2,req,name=value_status_info" json:"value_status_info,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgActivityValueStatusChangeNotify) Reset()         { *m = MsgActivityValueStatusChangeNotify{} }
func (m *MsgActivityValueStatusChangeNotify) String() string { return proto.CompactTextString(m) }
func (*MsgActivityValueStatusChangeNotify) ProtoMessage()    {}

func (m *MsgActivityValueStatusChangeNotify) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgActivityValueStatusChangeNotify) GetValueStatusInfo() int64 {
	if m != nil && m.ValueStatusInfo != nil {
		return *m.ValueStatusInfo
	}
	return 0
}

func (m *MsgActivityValueStatusChangeNotify) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *MsgActivityValueStatusChangeNotify) SetValueStatusInfo(value int64) {
	if m != nil {
		if m.ValueStatusInfo != nil {
			*m.ValueStatusInfo = value
			return
		}
		m.ValueStatusInfo = proto.Int64(value)
	}
}

func init() {
	proto.RegisterEnum("protocol.ActivityOpenFlag", ActivityOpenFlag_name, ActivityOpenFlag_value)
	proto.RegisterEnum("protocol.ActivityStatusFlag", ActivityStatusFlag_name, ActivityStatusFlag_value)
}
