// Code generated by protoc-gen-go.
// source: king_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KingSkill struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	Lv               *int32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Timestamp        *int64 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KingSkill) Reset()         { *m = KingSkill{} }
func (m *KingSkill) String() string { return proto.CompactTextString(m) }
func (*KingSkill) ProtoMessage()    {}

func (m *KingSkill) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *KingSkill) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *KingSkill) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *KingSkill) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *KingSkill) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *KingSkill) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

type KingCache struct {
	KingLv           *int32               `protobuf:"varint,1,req,name=king_lv" json:"king_lv,omitempty"`
	KingSkills       map[int32]*KingSkill `protobuf:"bytes,2,rep,name=king_skills" json:"king_skills,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *KingCache) Reset()         { *m = KingCache{} }
func (m *KingCache) String() string { return proto.CompactTextString(m) }
func (*KingCache) ProtoMessage()    {}

func (m *KingCache) GetKingLv() int32 {
	if m != nil && m.KingLv != nil {
		return *m.KingLv
	}
	return 0
}

func (m *KingCache) GetKingSkills() map[int32]*KingSkill {
	if m != nil {
		return m.KingSkills
	}
	return nil
}

func (m *KingCache) SetKingLv(value int32) {
	if m != nil {
		if m.KingLv != nil {
			*m.KingLv = value
			return
		}
		m.KingLv = proto.Int32(value)
	}
}

func (m *KingCache) SetKingSkills(value map[int32]*KingSkill) {
	if m != nil {
		m.KingSkills = value
	}
}

func init() {
}
