// Code generated by protoc-gen-go.
// source: mall_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MallCache struct {
	MallList         map[int32]int64 `protobuf:"bytes,1,rep,name=mall_list" json:"mall_list,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MallCache) Reset()         { *m = MallCache{} }
func (m *MallCache) String() string { return proto.CompactTextString(m) }
func (*MallCache) ProtoMessage()    {}

func (m *MallCache) GetMallList() map[int32]int64 {
	if m != nil {
		return m.MallList
	}
	return nil
}

func (m *MallCache) SetMallList(value map[int32]int64) {
	if m != nil {
		m.MallList = value
	}
}

func init() {
}
