package define

const (
	SysResetTime = iota + 1
	RoleLvInitial
	RoleExpInitial
	RoleLvMax
	RoleObtainInitial
	RoleSoulInitial
	RoleGoldInitial
	RoleOrderInitial
	RoleOrderRecover
	RoleModifyNicknameGold
	SoldierLvInitial
	SoldierExpInitial
	SoldierLvMax
	SoldierSkillLvInitial
	SoldierSkillLvMax
	HeroLvInitial
	HeroExpInitial
	HeroLvMax
	HeroSkillLvInitial
	HeroSkillLvMax
	HeroNumLimit
	HeroRankLimit
	BuildingLvInitial
	BuildingLvMax
	KingSkillLvInitial
	KingSkillLvMax
	StageNum
	StageOrdinarySweepNum
	StageEliteSweepNum
	ChatWordsLimit
	ChatInterval
	ChatWorldShowNum
	ChatPrivateShowNum
	ChatFreeTimeInitial
	ChatNeedGold
	ChatQueryLimitT
	FriendNumLimit
	FriendGiveAward
	FriendReceiveTime
	FriendVictoryNumInitial
	FriendFailureNumInitial
	AchievementNum
	DailyTaskNum
	SignInitial
	DropOneNeedGold
	DropOneNeedItemId
	DropOneNeedItemNum
	DropTenNeedGold
	DropTenNeedItemId
	DropTenNeedItemNum
	FillSoulParam1
	FillSoulParam2
	FillSoulParam3
	FillSoulParam4
	FillSoulPrice1
	FillSoulPrice2
	FillSoulPrice3
	FillSoulPrice4
	HeroCreateCD
	HeroCreateShockGold
	HeroCreateShockLife
	HeroCreateInitialLife
	OrderBuyNum
	OrderBuyTimeNum1
	OrderBuyTimeNum2
	OrderBuyTimeNum3
	OrderBuyTimeNum4
	OrderBuyCost1
	OrderBuyCost2
	OrderBuyCost3
	OrderBuyCost4
	OrderBuyCost5
	PlunderSearchLockTime
	PlunderBattleLockTime
	PlunderLostLockTime
	PlunderWinLockTime
	PlunderSearchUpLimit
	PlunderSearchDownLimit
	PlunderBattleTime
	PlunderReportLife
	PlunderReportTeam
	PlunderReportAttack
	PlunderSheildParam1
	PlunderSheildParam2
	PlunderSheildParam3
	PlunderSheildParam4
	PlunderSheildPrice1
	PlunderSheildPrice2
	PlunderSheildPrice3
	PlunderSheildPrice4
	PlunderRevengeCD
	PlunderBuyNum
	PlunderBuyTimeNum1
	PlunderBuyTimeNum2
	PlunderBuyTimeNum3
	PlunderBuyTimeNum4
	PlunderBuyCost1
	PlunderBuyCost2
	PlunderBuyCost3
	PlunderBuyCost4
	PlunderBuyCost5
	CombatPower1
	CombatPower2
	CombatPower3
	CombatPower4
	CombatPower5
	StageBuyNum
	StageBuyTimeNum1
	StageBuyTimeNum2
	StageBuyTimeNum3
	StageBuyTimeNum4
	StageBuyCost1
	StageBuyCost2
	StageBuyCost3
	StageBuyCost4
	StageBuyCost5
	PlunderChanceFree
	PlunderChanceGold
	PlunderChanceCost
	ArenaCostOrder
	ArenaChangeBossTime
	ArenaChangeShopTime
	BattleHeroEnergyRecover1
	BattleHeroEnergyRecover2
	BattleHeroEnergyRecover3
	BattleHeroEnergyRecover4
	AttackHeroEnergyRecover1
	AttackHeroEnergyRecover2
	AttackHeroEnergyRecover3
	AttackHeroEnergyRecover4
	BattleHeroHpPlus
	BattleHeroAtkPlus
	BattleSoldierHpPlus
	BattleSoldierAtkPlus
	GuideNpcLv
	GuideNpcName
	GuideNpcHero
	GuideNpcHeroFeatures1
	GuideNpcHeroFeatures2
	GuidePlunderAward
	GuidePlunderStep
	ChallengeLimit
	ChallengeResetTimes
	ChallengeResetCost
	ChallengeChance
	PlunderSysSoldier
	PlunderSysHpPlus
	PlunderSysAtkPlus
)
