// Code generated by protoc-gen-go.
// source: soldier_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SoldierCache struct {
	SchemeId          *int32          `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Num               *int32          `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	Level             *int32          `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Stage             *int32          `protobuf:"varint,4,req,name=stage" json:"stage,omitempty"`
	SkillLevel        map[int32]int32 `protobuf:"bytes,5,rep,name=skillLevel" json:"skillLevel,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Exp               *int32          `protobuf:"varint,6,req,name=exp" json:"exp,omitempty"`
	Timestamp         *int64          `protobuf:"varint,7,req,name=timestamp" json:"timestamp,omitempty"`
	EvoSpeedTimeStamp *int64          `protobuf:"varint,8,req,name=evoSpeedTimeStamp" json:"evoSpeedTimeStamp,omitempty"`
	Active            *int32          `protobuf:"varint,9,req,name=active" json:"active,omitempty"`
	AutoId            *int64          `protobuf:"varint,10,req,name=autoId" json:"autoId,omitempty"`
	XXX_unrecognized  []byte          `json:"-"`
}

func (m *SoldierCache) Reset()         { *m = SoldierCache{} }
func (m *SoldierCache) String() string { return proto.CompactTextString(m) }
func (*SoldierCache) ProtoMessage()    {}

func (m *SoldierCache) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *SoldierCache) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *SoldierCache) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SoldierCache) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *SoldierCache) GetSkillLevel() map[int32]int32 {
	if m != nil {
		return m.SkillLevel
	}
	return nil
}

func (m *SoldierCache) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *SoldierCache) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *SoldierCache) GetEvoSpeedTimeStamp() int64 {
	if m != nil && m.EvoSpeedTimeStamp != nil {
		return *m.EvoSpeedTimeStamp
	}
	return 0
}

func (m *SoldierCache) GetActive() int32 {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return 0
}

func (m *SoldierCache) GetAutoId() int64 {
	if m != nil && m.AutoId != nil {
		return *m.AutoId
	}
	return 0
}

func (m *SoldierCache) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *SoldierCache) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

func (m *SoldierCache) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *SoldierCache) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

func (m *SoldierCache) SetSkillLevel(value map[int32]int32) {
	if m != nil {
		m.SkillLevel = value
	}
}

func (m *SoldierCache) SetExp(value int32) {
	if m != nil {
		if m.Exp != nil {
			*m.Exp = value
			return
		}
		m.Exp = proto.Int32(value)
	}
}

func (m *SoldierCache) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *SoldierCache) SetEvoSpeedTimeStamp(value int64) {
	if m != nil {
		if m.EvoSpeedTimeStamp != nil {
			*m.EvoSpeedTimeStamp = value
			return
		}
		m.EvoSpeedTimeStamp = proto.Int64(value)
	}
}

func (m *SoldierCache) SetActive(value int32) {
	if m != nil {
		if m.Active != nil {
			*m.Active = value
			return
		}
		m.Active = proto.Int32(value)
	}
}

func (m *SoldierCache) SetAutoId(value int64) {
	if m != nil {
		if m.AutoId != nil {
			*m.AutoId = value
			return
		}
		m.AutoId = proto.Int64(value)
	}
}

type SoldierEventCache struct {
	EventId          *int32 `protobuf:"varint,1,req,name=eventId" json:"eventId,omitempty"`
	StartTime        *int64 `protobuf:"varint,2,req,name=startTime" json:"startTime,omitempty"`
	EndTime          *int64 `protobuf:"varint,3,req,name=endTime" json:"endTime,omitempty"`
	Duration         *int64 `protobuf:"varint,4,req,name=duration" json:"duration,omitempty"`
	EventType        *int32 `protobuf:"varint,5,req,name=eventType" json:"eventType,omitempty"`
	Remote           *int32 `protobuf:"varint,6,req,name=remote" json:"remote,omitempty"`
	Local            *int32 `protobuf:"varint,7,req,name=local" json:"local,omitempty"`
	LevelTotal       *int32 `protobuf:"varint,8,opt,name=levelTotal" json:"levelTotal,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SoldierEventCache) Reset()         { *m = SoldierEventCache{} }
func (m *SoldierEventCache) String() string { return proto.CompactTextString(m) }
func (*SoldierEventCache) ProtoMessage()    {}

func (m *SoldierEventCache) GetEventId() int32 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *SoldierEventCache) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *SoldierEventCache) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *SoldierEventCache) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *SoldierEventCache) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *SoldierEventCache) GetRemote() int32 {
	if m != nil && m.Remote != nil {
		return *m.Remote
	}
	return 0
}

func (m *SoldierEventCache) GetLocal() int32 {
	if m != nil && m.Local != nil {
		return *m.Local
	}
	return 0
}

func (m *SoldierEventCache) GetLevelTotal() int32 {
	if m != nil && m.LevelTotal != nil {
		return *m.LevelTotal
	}
	return 0
}

func (m *SoldierEventCache) SetEventId(value int32) {
	if m != nil {
		if m.EventId != nil {
			*m.EventId = value
			return
		}
		m.EventId = proto.Int32(value)
	}
}

func (m *SoldierEventCache) SetStartTime(value int64) {
	if m != nil {
		if m.StartTime != nil {
			*m.StartTime = value
			return
		}
		m.StartTime = proto.Int64(value)
	}
}

func (m *SoldierEventCache) SetEndTime(value int64) {
	if m != nil {
		if m.EndTime != nil {
			*m.EndTime = value
			return
		}
		m.EndTime = proto.Int64(value)
	}
}

func (m *SoldierEventCache) SetDuration(value int64) {
	if m != nil {
		if m.Duration != nil {
			*m.Duration = value
			return
		}
		m.Duration = proto.Int64(value)
	}
}

func (m *SoldierEventCache) SetEventType(value int32) {
	if m != nil {
		if m.EventType != nil {
			*m.EventType = value
			return
		}
		m.EventType = proto.Int32(value)
	}
}

func (m *SoldierEventCache) SetRemote(value int32) {
	if m != nil {
		if m.Remote != nil {
			*m.Remote = value
			return
		}
		m.Remote = proto.Int32(value)
	}
}

func (m *SoldierEventCache) SetLocal(value int32) {
	if m != nil {
		if m.Local != nil {
			*m.Local = value
			return
		}
		m.Local = proto.Int32(value)
	}
}

func (m *SoldierEventCache) SetLevelTotal(value int32) {
	if m != nil {
		if m.LevelTotal != nil {
			*m.LevelTotal = value
			return
		}
		m.LevelTotal = proto.Int32(value)
	}
}

func init() {
}
