// Code generated by protoc-gen-go.
// source: hero_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HeroSkillCache struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	SkillLv          *int32 `protobuf:"varint,2,req,name=skill_lv" json:"skill_lv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroSkillCache) Reset()         { *m = HeroSkillCache{} }
func (m *HeroSkillCache) String() string { return proto.CompactTextString(m) }
func (*HeroSkillCache) ProtoMessage()    {}

func (m *HeroSkillCache) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *HeroSkillCache) GetSkillLv() int32 {
	if m != nil && m.SkillLv != nil {
		return *m.SkillLv
	}
	return 0
}

func (m *HeroSkillCache) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *HeroSkillCache) SetSkillLv(value int32) {
	if m != nil {
		if m.SkillLv != nil {
			*m.SkillLv = value
			return
		}
		m.SkillLv = proto.Int32(value)
	}
}

type HeroCache struct {
	SchemeId         *int32                    `protobuf:"varint,1,req,name=scheme_id" json:"scheme_id,omitempty"`
	Lv               *int32                    `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Stage            *int32                    `protobuf:"varint,3,req,name=stage" json:"stage,omitempty"`
	Rank             *int32                    `protobuf:"varint,4,req,name=rank" json:"rank,omitempty"`
	RankExp          *int32                    `protobuf:"varint,5,req,name=rank_exp" json:"rank_exp,omitempty"`
	SkillList        map[int32]*HeroSkillCache `protobuf:"bytes,6,rep,name=skill_list" json:"skill_list,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *HeroCache) Reset()         { *m = HeroCache{} }
func (m *HeroCache) String() string { return proto.CompactTextString(m) }
func (*HeroCache) ProtoMessage()    {}

func (m *HeroCache) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *HeroCache) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *HeroCache) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *HeroCache) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *HeroCache) GetRankExp() int32 {
	if m != nil && m.RankExp != nil {
		return *m.RankExp
	}
	return 0
}

func (m *HeroCache) GetSkillList() map[int32]*HeroSkillCache {
	if m != nil {
		return m.SkillList
	}
	return nil
}

func (m *HeroCache) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *HeroCache) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *HeroCache) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

func (m *HeroCache) SetRank(value int32) {
	if m != nil {
		if m.Rank != nil {
			*m.Rank = value
			return
		}
		m.Rank = proto.Int32(value)
	}
}

func (m *HeroCache) SetRankExp(value int32) {
	if m != nil {
		if m.RankExp != nil {
			*m.RankExp = value
			return
		}
		m.RankExp = proto.Int32(value)
	}
}

func (m *HeroCache) SetSkillList(value map[int32]*HeroSkillCache) {
	if m != nil {
		m.SkillList = value
	}
}

func init() {
}
