// Code generated by protoc-gen-go.
// source: king.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KingSkill struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	Lv               *int32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Timestamp        *int64 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KingSkill) Reset()         { *m = KingSkill{} }
func (m *KingSkill) String() string { return proto.CompactTextString(m) }
func (*KingSkill) ProtoMessage()    {}

func (m *KingSkill) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *KingSkill) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *KingSkill) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *KingSkill) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *KingSkill) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *KingSkill) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

type KingInfo struct {
	KingLv           *int32       `protobuf:"varint,1,req,name=king_lv" json:"king_lv,omitempty"`
	KingSkills       []*KingSkill `protobuf:"bytes,2,rep,name=king_skills" json:"king_skills,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KingInfo) Reset()         { *m = KingInfo{} }
func (m *KingInfo) String() string { return proto.CompactTextString(m) }
func (*KingInfo) ProtoMessage()    {}

func (m *KingInfo) GetKingLv() int32 {
	if m != nil && m.KingLv != nil {
		return *m.KingLv
	}
	return 0
}

func (m *KingInfo) GetKingSkills() []*KingSkill {
	if m != nil {
		return m.KingSkills
	}
	return nil
}

func (m *KingInfo) SetKingLv(value int32) {
	if m != nil {
		if m.KingLv != nil {
			*m.KingLv = value
			return
		}
		m.KingLv = proto.Int32(value)
	}
}

func (m *KingInfo) SetKingSkills(value []*KingSkill) {
	if m != nil {
		m.KingSkills = value
	}
}

type MsgKingSkillNotify struct {
	KingSkill        *KingSkill `protobuf:"bytes,1,req,name=kingSkill" json:"kingSkill,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MsgKingSkillNotify) Reset()         { *m = MsgKingSkillNotify{} }
func (m *MsgKingSkillNotify) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillNotify) ProtoMessage()    {}

func (m *MsgKingSkillNotify) GetKingSkill() *KingSkill {
	if m != nil {
		return m.KingSkill
	}
	return nil
}

func (m *MsgKingSkillNotify) SetKingSkill(value *KingSkill) {
	if m != nil {
		m.KingSkill = value
	}
}

// 开始技能升级
type MsgKingSkillStartLvUpReq struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	UsedCoin         *bool  `protobuf:"varint,2,req,name=used_coin" json:"used_coin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillStartLvUpReq) Reset()         { *m = MsgKingSkillStartLvUpReq{} }
func (m *MsgKingSkillStartLvUpReq) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillStartLvUpReq) ProtoMessage()    {}

func (m *MsgKingSkillStartLvUpReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgKingSkillStartLvUpReq) GetUsedCoin() bool {
	if m != nil && m.UsedCoin != nil {
		return *m.UsedCoin
	}
	return false
}

func (m *MsgKingSkillStartLvUpReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *MsgKingSkillStartLvUpReq) SetUsedCoin(value bool) {
	if m != nil {
		if m.UsedCoin != nil {
			*m.UsedCoin = value
			return
		}
		m.UsedCoin = proto.Bool(value)
	}
}

type MsgKingSkillStartLvUpRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillStartLvUpRet) Reset()         { *m = MsgKingSkillStartLvUpRet{} }
func (m *MsgKingSkillStartLvUpRet) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillStartLvUpRet) ProtoMessage()    {}

func (m *MsgKingSkillStartLvUpRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgKingSkillStartLvUpRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 使用货币移除升级时间
type MsgKingSkillLvUpRemoveTimeReq struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillLvUpRemoveTimeReq) Reset()         { *m = MsgKingSkillLvUpRemoveTimeReq{} }
func (m *MsgKingSkillLvUpRemoveTimeReq) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillLvUpRemoveTimeReq) ProtoMessage()    {}

func (m *MsgKingSkillLvUpRemoveTimeReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgKingSkillLvUpRemoveTimeReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

type MsgKingSkillLvUpRemoveTimeRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillLvUpRemoveTimeRet) Reset()         { *m = MsgKingSkillLvUpRemoveTimeRet{} }
func (m *MsgKingSkillLvUpRemoveTimeRet) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillLvUpRemoveTimeRet) ProtoMessage()    {}

func (m *MsgKingSkillLvUpRemoveTimeRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgKingSkillLvUpRemoveTimeRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 检查技能升级是否完成升级
type MsgKingSkillFinishLvUpReq struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillFinishLvUpReq) Reset()         { *m = MsgKingSkillFinishLvUpReq{} }
func (m *MsgKingSkillFinishLvUpReq) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillFinishLvUpReq) ProtoMessage()    {}

func (m *MsgKingSkillFinishLvUpReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgKingSkillFinishLvUpReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

type MsgKingSkillFinishLvUpRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillFinishLvUpRet) Reset()         { *m = MsgKingSkillFinishLvUpRet{} }
func (m *MsgKingSkillFinishLvUpRet) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillFinishLvUpRet) ProtoMessage()    {}

func (m *MsgKingSkillFinishLvUpRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgKingSkillFinishLvUpRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 取消技能升级
type MsgKingSkillCancelLvUpReq struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skill_id" json:"skill_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillCancelLvUpReq) Reset()         { *m = MsgKingSkillCancelLvUpReq{} }
func (m *MsgKingSkillCancelLvUpReq) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillCancelLvUpReq) ProtoMessage()    {}

func (m *MsgKingSkillCancelLvUpReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgKingSkillCancelLvUpReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

type MsgKingSkillCancelLvUpRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingSkillCancelLvUpRet) Reset()         { *m = MsgKingSkillCancelLvUpRet{} }
func (m *MsgKingSkillCancelLvUpRet) String() string { return proto.CompactTextString(m) }
func (*MsgKingSkillCancelLvUpRet) ProtoMessage()    {}

func (m *MsgKingSkillCancelLvUpRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgKingSkillCancelLvUpRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 等级提升
type MsgKingAddLvReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingAddLvReq) Reset()         { *m = MsgKingAddLvReq{} }
func (m *MsgKingAddLvReq) String() string { return proto.CompactTextString(m) }
func (*MsgKingAddLvReq) ProtoMessage()    {}

type MsgKingAddLvRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgKingAddLvRet) Reset()         { *m = MsgKingAddLvRet{} }
func (m *MsgKingAddLvRet) String() string { return proto.CompactTextString(m) }
func (*MsgKingAddLvRet) ProtoMessage()    {}

func (m *MsgKingAddLvRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgKingAddLvRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func init() {
}
