// Code generated by protoc-gen-go.
// source: fb.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Fb struct {
	SchemeId         *int32           `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	AttackedTimes    []*AttackedTimes `protobuf:"bytes,2,rep,name=attackedTimes" json:"attackedTimes,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Fb) Reset()         { *m = Fb{} }
func (m *Fb) String() string { return proto.CompactTextString(m) }
func (*Fb) ProtoMessage()    {}

func (m *Fb) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *Fb) GetAttackedTimes() []*AttackedTimes {
	if m != nil {
		return m.AttackedTimes
	}
	return nil
}

func (m *Fb) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *Fb) SetAttackedTimes(value []*AttackedTimes) {
	if m != nil {
		m.AttackedTimes = value
	}
}

type AttackedTimes struct {
	Difficulty       *int32 `protobuf:"varint,1,req,name=difficulty" json:"difficulty,omitempty"`
	Times            *int32 `protobuf:"varint,2,req,name=times" json:"times,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AttackedTimes) Reset()         { *m = AttackedTimes{} }
func (m *AttackedTimes) String() string { return proto.CompactTextString(m) }
func (*AttackedTimes) ProtoMessage()    {}

func (m *AttackedTimes) GetDifficulty() int32 {
	if m != nil && m.Difficulty != nil {
		return *m.Difficulty
	}
	return 0
}

func (m *AttackedTimes) GetTimes() int32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

func (m *AttackedTimes) SetDifficulty(value int32) {
	if m != nil {
		if m.Difficulty != nil {
			*m.Difficulty = value
			return
		}
		m.Difficulty = proto.Int32(value)
	}
}

func (m *AttackedTimes) SetTimes(value int32) {
	if m != nil {
		if m.Times != nil {
			*m.Times = value
			return
		}
		m.Times = proto.Int32(value)
	}
}

type CaughtNpc struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Num              *int32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CaughtNpc) Reset()         { *m = CaughtNpc{} }
func (m *CaughtNpc) String() string { return proto.CompactTextString(m) }
func (*CaughtNpc) ProtoMessage()    {}

func (m *CaughtNpc) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *CaughtNpc) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *CaughtNpc) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *CaughtNpc) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

type MsgFbAllReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFbAllReq) Reset()         { *m = MsgFbAllReq{} }
func (m *MsgFbAllReq) String() string { return proto.CompactTextString(m) }
func (*MsgFbAllReq) ProtoMessage()    {}

type MsgFbAllRet struct {
	Fbs              []*Fb  `protobuf:"bytes,1,rep,name=fbs" json:"fbs,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFbAllRet) Reset()         { *m = MsgFbAllRet{} }
func (m *MsgFbAllRet) String() string { return proto.CompactTextString(m) }
func (*MsgFbAllRet) ProtoMessage()    {}

func (m *MsgFbAllRet) GetFbs() []*Fb {
	if m != nil {
		return m.Fbs
	}
	return nil
}

func (m *MsgFbAllRet) SetFbs(value []*Fb) {
	if m != nil {
		m.Fbs = value
	}
}

// 副本开始
type MsgFbBeginReq struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Difficulty       *int32 `protobuf:"varint,2,req,name=difficulty" json:"difficulty,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFbBeginReq) Reset()         { *m = MsgFbBeginReq{} }
func (m *MsgFbBeginReq) String() string { return proto.CompactTextString(m) }
func (*MsgFbBeginReq) ProtoMessage()    {}

func (m *MsgFbBeginReq) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgFbBeginReq) GetDifficulty() int32 {
	if m != nil && m.Difficulty != nil {
		return *m.Difficulty
	}
	return 0
}

func (m *MsgFbBeginReq) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgFbBeginReq) SetDifficulty(value int32) {
	if m != nil {
		if m.Difficulty != nil {
			*m.Difficulty = value
			return
		}
		m.Difficulty = proto.Int32(value)
	}
}

type MsgFbBeginRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFbBeginRet) Reset()         { *m = MsgFbBeginRet{} }
func (m *MsgFbBeginRet) String() string { return proto.CompactTextString(m) }
func (*MsgFbBeginRet) ProtoMessage()    {}

func (m *MsgFbBeginRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFbBeginRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 完成，领取奖励
type MsgFbFinishReq struct {
	SchemeId         *int32       `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Difficulty       *int32       `protobuf:"varint,2,req,name=difficulty" json:"difficulty,omitempty"`
	IsPassed         *bool        `protobuf:"varint,3,req,name=isPassed" json:"isPassed,omitempty"`
	CaughtNpc        []*CaughtNpc `protobuf:"bytes,4,rep,name=caughtNpc" json:"caughtNpc,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgFbFinishReq) Reset()         { *m = MsgFbFinishReq{} }
func (m *MsgFbFinishReq) String() string { return proto.CompactTextString(m) }
func (*MsgFbFinishReq) ProtoMessage()    {}

func (m *MsgFbFinishReq) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgFbFinishReq) GetDifficulty() int32 {
	if m != nil && m.Difficulty != nil {
		return *m.Difficulty
	}
	return 0
}

func (m *MsgFbFinishReq) GetIsPassed() bool {
	if m != nil && m.IsPassed != nil {
		return *m.IsPassed
	}
	return false
}

func (m *MsgFbFinishReq) GetCaughtNpc() []*CaughtNpc {
	if m != nil {
		return m.CaughtNpc
	}
	return nil
}

func (m *MsgFbFinishReq) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgFbFinishReq) SetDifficulty(value int32) {
	if m != nil {
		if m.Difficulty != nil {
			*m.Difficulty = value
			return
		}
		m.Difficulty = proto.Int32(value)
	}
}

func (m *MsgFbFinishReq) SetIsPassed(value bool) {
	if m != nil {
		if m.IsPassed != nil {
			*m.IsPassed = value
			return
		}
		m.IsPassed = proto.Bool(value)
	}
}

func (m *MsgFbFinishReq) SetCaughtNpc(value []*CaughtNpc) {
	if m != nil {
		m.CaughtNpc = value
	}
}

type MsgFbFinishRet struct {
	RetCode          *int32  `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	Awards           []int32 `protobuf:"varint,2,rep,name=awards" json:"awards,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFbFinishRet) Reset()         { *m = MsgFbFinishRet{} }
func (m *MsgFbFinishRet) String() string { return proto.CompactTextString(m) }
func (*MsgFbFinishRet) ProtoMessage()    {}

func (m *MsgFbFinishRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFbFinishRet) GetAwards() []int32 {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgFbFinishRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgFbFinishRet) SetAwards(value []int32) {
	if m != nil {
		m.Awards = value
	}
}

func init() {
}
