// Code generated by protoc-gen-go.
// source: friend.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Friend struct {
	Id                    *int64      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	SelfId                *int64      `protobuf:"varint,2,req,name=selfId" json:"selfId,omitempty"`
	WinTimes              *int32      `protobuf:"varint,3,req,name=winTimes" json:"winTimes,omitempty"`
	LoseTimes             *int32      `protobuf:"varint,4,req,name=loseTimes" json:"loseTimes,omitempty"`
	SendExcitationTime    *int64      `protobuf:"varint,5,req,name=sendExcitationTime" json:"sendExcitationTime,omitempty"`
	ReceiveExcitationTime *int64      `protobuf:"varint,6,req,name=receiveExcitationTime" json:"receiveExcitationTime,omitempty"`
	UseExcitationTime     *int64      `protobuf:"varint,7,req,name=useExcitationTime" json:"useExcitationTime,omitempty"`
	FriendInfo            *FriendInfo `protobuf:"bytes,8,req,name=friendInfo" json:"friendInfo,omitempty"`
	XXX_unrecognized      []byte      `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}

func (m *Friend) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Friend) GetSelfId() int64 {
	if m != nil && m.SelfId != nil {
		return *m.SelfId
	}
	return 0
}

func (m *Friend) GetWinTimes() int32 {
	if m != nil && m.WinTimes != nil {
		return *m.WinTimes
	}
	return 0
}

func (m *Friend) GetLoseTimes() int32 {
	if m != nil && m.LoseTimes != nil {
		return *m.LoseTimes
	}
	return 0
}

func (m *Friend) GetSendExcitationTime() int64 {
	if m != nil && m.SendExcitationTime != nil {
		return *m.SendExcitationTime
	}
	return 0
}

func (m *Friend) GetReceiveExcitationTime() int64 {
	if m != nil && m.ReceiveExcitationTime != nil {
		return *m.ReceiveExcitationTime
	}
	return 0
}

func (m *Friend) GetUseExcitationTime() int64 {
	if m != nil && m.UseExcitationTime != nil {
		return *m.UseExcitationTime
	}
	return 0
}

func (m *Friend) GetFriendInfo() *FriendInfo {
	if m != nil {
		return m.FriendInfo
	}
	return nil
}

func (m *Friend) SetId(value int64) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int64(value)
	}
}

func (m *Friend) SetSelfId(value int64) {
	if m != nil {
		if m.SelfId != nil {
			*m.SelfId = value
			return
		}
		m.SelfId = proto.Int64(value)
	}
}

func (m *Friend) SetWinTimes(value int32) {
	if m != nil {
		if m.WinTimes != nil {
			*m.WinTimes = value
			return
		}
		m.WinTimes = proto.Int32(value)
	}
}

func (m *Friend) SetLoseTimes(value int32) {
	if m != nil {
		if m.LoseTimes != nil {
			*m.LoseTimes = value
			return
		}
		m.LoseTimes = proto.Int32(value)
	}
}

func (m *Friend) SetSendExcitationTime(value int64) {
	if m != nil {
		if m.SendExcitationTime != nil {
			*m.SendExcitationTime = value
			return
		}
		m.SendExcitationTime = proto.Int64(value)
	}
}

func (m *Friend) SetReceiveExcitationTime(value int64) {
	if m != nil {
		if m.ReceiveExcitationTime != nil {
			*m.ReceiveExcitationTime = value
			return
		}
		m.ReceiveExcitationTime = proto.Int64(value)
	}
}

func (m *Friend) SetUseExcitationTime(value int64) {
	if m != nil {
		if m.UseExcitationTime != nil {
			*m.UseExcitationTime = value
			return
		}
		m.UseExcitationTime = proto.Int64(value)
	}
}

func (m *Friend) SetFriendInfo(value *FriendInfo) {
	if m != nil {
		m.FriendInfo = value
	}
}

type FriendInfo struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	LoginTime        *int64  `protobuf:"varint,2,req,name=loginTime" json:"loginTime,omitempty"`
	Level            *int32  `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	LeagueLevel      *int32  `protobuf:"varint,4,req,name=leagueLevel" json:"leagueLevel,omitempty"`
	Trophy           *int32  `protobuf:"varint,5,req,name=trophy" json:"trophy,omitempty"`
	Timestamp        *int64  `protobuf:"varint,6,req,name=timestamp" json:"timestamp,omitempty"`
	Nickname         *string `protobuf:"bytes,7,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendInfo) Reset()         { *m = FriendInfo{} }
func (m *FriendInfo) String() string { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()    {}

func (m *FriendInfo) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *FriendInfo) GetLoginTime() int64 {
	if m != nil && m.LoginTime != nil {
		return *m.LoginTime
	}
	return 0
}

func (m *FriendInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *FriendInfo) GetLeagueLevel() int32 {
	if m != nil && m.LeagueLevel != nil {
		return *m.LeagueLevel
	}
	return 0
}

func (m *FriendInfo) GetTrophy() int32 {
	if m != nil && m.Trophy != nil {
		return *m.Trophy
	}
	return 0
}

func (m *FriendInfo) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *FriendInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *FriendInfo) SetId(value int64) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int64(value)
	}
}

func (m *FriendInfo) SetLoginTime(value int64) {
	if m != nil {
		if m.LoginTime != nil {
			*m.LoginTime = value
			return
		}
		m.LoginTime = proto.Int64(value)
	}
}

func (m *FriendInfo) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *FriendInfo) SetLeagueLevel(value int32) {
	if m != nil {
		if m.LeagueLevel != nil {
			*m.LeagueLevel = value
			return
		}
		m.LeagueLevel = proto.Int32(value)
	}
}

func (m *FriendInfo) SetTrophy(value int32) {
	if m != nil {
		if m.Trophy != nil {
			*m.Trophy = value
			return
		}
		m.Trophy = proto.Int32(value)
	}
}

func (m *FriendInfo) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *FriendInfo) SetNickname(value string) {
	if m != nil {
		if m.Nickname != nil {
			*m.Nickname = value
			return
		}
		m.Nickname = proto.String(value)
	}
}

type FriendRequest struct {
	Id               *int64      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	SelfId           *int64      `protobuf:"varint,2,req,name=selfId" json:"selfId,omitempty"`
	Timestamp        *int64      `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	FriendInfo       *FriendInfo `protobuf:"bytes,4,req,name=friendInfo" json:"friendInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}

func (m *FriendRequest) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *FriendRequest) GetSelfId() int64 {
	if m != nil && m.SelfId != nil {
		return *m.SelfId
	}
	return 0
}

func (m *FriendRequest) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *FriendRequest) GetFriendInfo() *FriendInfo {
	if m != nil {
		return m.FriendInfo
	}
	return nil
}

func (m *FriendRequest) SetId(value int64) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int64(value)
	}
}

func (m *FriendRequest) SetSelfId(value int64) {
	if m != nil {
		if m.SelfId != nil {
			*m.SelfId = value
			return
		}
		m.SelfId = proto.Int64(value)
	}
}

func (m *FriendRequest) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *FriendRequest) SetFriendInfo(value *FriendInfo) {
	if m != nil {
		m.FriendInfo = value
	}
}

type MsgFriendAllReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendAllReq) Reset()         { *m = MsgFriendAllReq{} }
func (m *MsgFriendAllReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendAllReq) ProtoMessage()    {}

type MsgFriendAllRet struct {
	Friends          []*Friend `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MsgFriendAllRet) Reset()         { *m = MsgFriendAllRet{} }
func (m *MsgFriendAllRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendAllRet) ProtoMessage()    {}

func (m *MsgFriendAllRet) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *MsgFriendAllRet) SetFriends(value []*Friend) {
	if m != nil {
		m.Friends = value
	}
}

// 搜索好友
type MsgFriendSearchReq struct {
	Alias            *string `protobuf:"bytes,1,req,name=alias" json:"alias,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFriendSearchReq) Reset()         { *m = MsgFriendSearchReq{} }
func (m *MsgFriendSearchReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSearchReq) ProtoMessage()    {}

func (m *MsgFriendSearchReq) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func (m *MsgFriendSearchReq) SetAlias(value string) {
	if m != nil {
		if m.Alias != nil {
			*m.Alias = value
			return
		}
		m.Alias = proto.String(value)
	}
}

type MsgFriendSearchRet struct {
	RetCode          *int32  `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	Friend           *Friend `protobuf:"bytes,2,opt,name=friend" json:"friend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFriendSearchRet) Reset()         { *m = MsgFriendSearchRet{} }
func (m *MsgFriendSearchRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSearchRet) ProtoMessage()    {}

func (m *MsgFriendSearchRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendSearchRet) GetFriend() *Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

func (m *MsgFriendSearchRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgFriendSearchRet) SetFriend(value *Friend) {
	if m != nil {
		m.Friend = value
	}
}

// 删除好友
type MsgFriendDeleteReq struct {
	FriendIds        []int64 `protobuf:"varint,1,rep,name=friendIds" json:"friendIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFriendDeleteReq) Reset()         { *m = MsgFriendDeleteReq{} }
func (m *MsgFriendDeleteReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendDeleteReq) ProtoMessage()    {}

func (m *MsgFriendDeleteReq) GetFriendIds() []int64 {
	if m != nil {
		return m.FriendIds
	}
	return nil
}

func (m *MsgFriendDeleteReq) SetFriendIds(value []int64) {
	if m != nil {
		m.FriendIds = value
	}
}

type MsgFriendDeleteRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendDeleteRet) Reset()         { *m = MsgFriendDeleteRet{} }
func (m *MsgFriendDeleteRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendDeleteRet) ProtoMessage()    {}

func (m *MsgFriendDeleteRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendDeleteRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 发送激励
type MsgFriendSendExcitationReq struct {
	FriendIds        []int64 `protobuf:"varint,1,rep,name=friendIds" json:"friendIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFriendSendExcitationReq) Reset()         { *m = MsgFriendSendExcitationReq{} }
func (m *MsgFriendSendExcitationReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSendExcitationReq) ProtoMessage()    {}

func (m *MsgFriendSendExcitationReq) GetFriendIds() []int64 {
	if m != nil {
		return m.FriendIds
	}
	return nil
}

func (m *MsgFriendSendExcitationReq) SetFriendIds(value []int64) {
	if m != nil {
		m.FriendIds = value
	}
}

type MsgFriendSendExcitationRet struct {
	AffectedRows     *int32 `protobuf:"varint,1,req,name=affectedRows" json:"affectedRows,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendSendExcitationRet) Reset()         { *m = MsgFriendSendExcitationRet{} }
func (m *MsgFriendSendExcitationRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSendExcitationRet) ProtoMessage()    {}

func (m *MsgFriendSendExcitationRet) GetAffectedRows() int32 {
	if m != nil && m.AffectedRows != nil {
		return *m.AffectedRows
	}
	return 0
}

func (m *MsgFriendSendExcitationRet) SetAffectedRows(value int32) {
	if m != nil {
		if m.AffectedRows != nil {
			*m.AffectedRows = value
			return
		}
		m.AffectedRows = proto.Int32(value)
	}
}

// 接收激励
type MsgFriendUseExcitationReq struct {
	FriendIds        []int64 `protobuf:"varint,1,rep,name=friendIds" json:"friendIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFriendUseExcitationReq) Reset()         { *m = MsgFriendUseExcitationReq{} }
func (m *MsgFriendUseExcitationReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendUseExcitationReq) ProtoMessage()    {}

func (m *MsgFriendUseExcitationReq) GetFriendIds() []int64 {
	if m != nil {
		return m.FriendIds
	}
	return nil
}

func (m *MsgFriendUseExcitationReq) SetFriendIds(value []int64) {
	if m != nil {
		m.FriendIds = value
	}
}

type MsgFriendUseExcitationRet struct {
	AffectedRows     *int32 `protobuf:"varint,2,req,name=affectedRows" json:"affectedRows,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendUseExcitationRet) Reset()         { *m = MsgFriendUseExcitationRet{} }
func (m *MsgFriendUseExcitationRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendUseExcitationRet) ProtoMessage()    {}

func (m *MsgFriendUseExcitationRet) GetAffectedRows() int32 {
	if m != nil && m.AffectedRows != nil {
		return *m.AffectedRows
	}
	return 0
}

func (m *MsgFriendUseExcitationRet) SetAffectedRows(value int32) {
	if m != nil {
		if m.AffectedRows != nil {
			*m.AffectedRows = value
			return
		}
		m.AffectedRows = proto.Int32(value)
	}
}

// 好友切磋
type MsgFriendSavePvpResultReq struct {
	FriendId         *int64 `protobuf:"varint,1,req,name=friendId" json:"friendId,omitempty"`
	AttackerWin      *bool  `protobuf:"varint,2,req,name=attackerWin" json:"attackerWin,omitempty"`
	Record           []byte `protobuf:"bytes,3,req,name=record" json:"record,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendSavePvpResultReq) Reset()         { *m = MsgFriendSavePvpResultReq{} }
func (m *MsgFriendSavePvpResultReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSavePvpResultReq) ProtoMessage()    {}

func (m *MsgFriendSavePvpResultReq) GetFriendId() int64 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *MsgFriendSavePvpResultReq) GetAttackerWin() bool {
	if m != nil && m.AttackerWin != nil {
		return *m.AttackerWin
	}
	return false
}

func (m *MsgFriendSavePvpResultReq) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *MsgFriendSavePvpResultReq) SetFriendId(value int64) {
	if m != nil {
		if m.FriendId != nil {
			*m.FriendId = value
			return
		}
		m.FriendId = proto.Int64(value)
	}
}

func (m *MsgFriendSavePvpResultReq) SetAttackerWin(value bool) {
	if m != nil {
		if m.AttackerWin != nil {
			*m.AttackerWin = value
			return
		}
		m.AttackerWin = proto.Bool(value)
	}
}

func (m *MsgFriendSavePvpResultReq) SetRecord(value []byte) {
	if m != nil {
		if m.Record != nil {
			m.Record = value
			return
		}
		m.Record = value
	}
}

type MsgFriendSavePvpResultRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendSavePvpResultRet) Reset()         { *m = MsgFriendSavePvpResultRet{} }
func (m *MsgFriendSavePvpResultRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendSavePvpResultRet) ProtoMessage()    {}

func (m *MsgFriendSavePvpResultRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendSavePvpResultRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 好友请求
type MsgFriendRequestAllReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendRequestAllReq) Reset()         { *m = MsgFriendRequestAllReq{} }
func (m *MsgFriendRequestAllReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestAllReq) ProtoMessage()    {}

type MsgFriendRequestAllRet struct {
	Requests         []*FriendRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgFriendRequestAllRet) Reset()         { *m = MsgFriendRequestAllRet{} }
func (m *MsgFriendRequestAllRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestAllRet) ProtoMessage()    {}

func (m *MsgFriendRequestAllRet) GetRequests() []*FriendRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *MsgFriendRequestAllRet) SetRequests(value []*FriendRequest) {
	if m != nil {
		m.Requests = value
	}
}

type MsgFriendRequestAddReq struct {
	FriendId         *int64 `protobuf:"varint,1,req,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendRequestAddReq) Reset()         { *m = MsgFriendRequestAddReq{} }
func (m *MsgFriendRequestAddReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestAddReq) ProtoMessage()    {}

func (m *MsgFriendRequestAddReq) GetFriendId() int64 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *MsgFriendRequestAddReq) SetFriendId(value int64) {
	if m != nil {
		if m.FriendId != nil {
			*m.FriendId = value
			return
		}
		m.FriendId = proto.Int64(value)
	}
}

type MsgFriendRequestAddRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendRequestAddRet) Reset()         { *m = MsgFriendRequestAddRet{} }
func (m *MsgFriendRequestAddRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestAddRet) ProtoMessage()    {}

func (m *MsgFriendRequestAddRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendRequestAddRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 处理好友请求
type MsgFriendRequestDealWithReq struct {
	FriendId         *int64 `protobuf:"varint,1,req,name=friendId" json:"friendId,omitempty"`
	IsAgreed         *bool  `protobuf:"varint,2,req,name=isAgreed" json:"isAgreed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendRequestDealWithReq) Reset()         { *m = MsgFriendRequestDealWithReq{} }
func (m *MsgFriendRequestDealWithReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestDealWithReq) ProtoMessage()    {}

func (m *MsgFriendRequestDealWithReq) GetFriendId() int64 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *MsgFriendRequestDealWithReq) GetIsAgreed() bool {
	if m != nil && m.IsAgreed != nil {
		return *m.IsAgreed
	}
	return false
}

func (m *MsgFriendRequestDealWithReq) SetFriendId(value int64) {
	if m != nil {
		if m.FriendId != nil {
			*m.FriendId = value
			return
		}
		m.FriendId = proto.Int64(value)
	}
}

func (m *MsgFriendRequestDealWithReq) SetIsAgreed(value bool) {
	if m != nil {
		if m.IsAgreed != nil {
			*m.IsAgreed = value
			return
		}
		m.IsAgreed = proto.Bool(value)
	}
}

type MsgFriendRequestDealWithRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendRequestDealWithRet) Reset()         { *m = MsgFriendRequestDealWithRet{} }
func (m *MsgFriendRequestDealWithRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendRequestDealWithRet) ProtoMessage()    {}

func (m *MsgFriendRequestDealWithRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendRequestDealWithRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 添加邀请者id
type MsgFriendInviteAddIdReq struct {
	InviteId         *int64 `protobuf:"varint,1,req,name=inviteId" json:"inviteId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendInviteAddIdReq) Reset()         { *m = MsgFriendInviteAddIdReq{} }
func (m *MsgFriendInviteAddIdReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendInviteAddIdReq) ProtoMessage()    {}

func (m *MsgFriendInviteAddIdReq) GetInviteId() int64 {
	if m != nil && m.InviteId != nil {
		return *m.InviteId
	}
	return 0
}

func (m *MsgFriendInviteAddIdReq) SetInviteId(value int64) {
	if m != nil {
		if m.InviteId != nil {
			*m.InviteId = value
			return
		}
		m.InviteId = proto.Int64(value)
	}
}

type MsgFriendInviteAddIdRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgFriendInviteAddIdRet) Reset()         { *m = MsgFriendInviteAddIdRet{} }
func (m *MsgFriendInviteAddIdRet) String() string { return proto.CompactTextString(m) }
func (*MsgFriendInviteAddIdRet) ProtoMessage()    {}

func (m *MsgFriendInviteAddIdRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgFriendInviteAddIdRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func init() {
}
