// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MsgLoginAuthReq struct {
	TokenKey         *string `protobuf:"bytes,1,req,name=token_key" json:"token_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLoginAuthReq) Reset()         { *m = MsgLoginAuthReq{} }
func (m *MsgLoginAuthReq) String() string { return proto.CompactTextString(m) }
func (*MsgLoginAuthReq) ProtoMessage()    {}

func (m *MsgLoginAuthReq) GetTokenKey() string {
	if m != nil && m.TokenKey != nil {
		return *m.TokenKey
	}
	return ""
}

func (m *MsgLoginAuthReq) SetTokenKey(value string) {
	if m != nil {
		if m.TokenKey != nil {
			*m.TokenKey = value
			return
		}
		m.TokenKey = proto.String(value)
	}
}

type MsgLoginAuthRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=ret_code" json:"ret_code,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgLoginAuthRet) Reset()         { *m = MsgLoginAuthRet{} }
func (m *MsgLoginAuthRet) String() string { return proto.CompactTextString(m) }
func (*MsgLoginAuthRet) ProtoMessage()    {}

func (m *MsgLoginAuthRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgLoginAuthRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

type MsgLoginInReq struct {
	TokenKey         *string `protobuf:"bytes,1,req,name=token_key" json:"token_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLoginInReq) Reset()         { *m = MsgLoginInReq{} }
func (m *MsgLoginInReq) String() string { return proto.CompactTextString(m) }
func (*MsgLoginInReq) ProtoMessage()    {}

func (m *MsgLoginInReq) GetTokenKey() string {
	if m != nil && m.TokenKey != nil {
		return *m.TokenKey
	}
	return ""
}

func (m *MsgLoginInReq) SetTokenKey(value string) {
	if m != nil {
		if m.TokenKey != nil {
			*m.TokenKey = value
			return
		}
		m.TokenKey = proto.String(value)
	}
}

type MsgLoginInRet struct {
	SystemTime         *int64              `protobuf:"varint,1,req,name=system_time" json:"system_time,omitempty"`
	RoleInfo           *RoleBaseInfo       `protobuf:"bytes,2,req,name=role_info" json:"role_info,omitempty"`
	ItemListInfo       *ItemListInfo       `protobuf:"bytes,3,req,name=item_list_info" json:"item_list_info,omitempty"`
	HeroCreateInfo     *HeroCreateInfo     `protobuf:"bytes,4,req,name=hero_create_info" json:"hero_create_info,omitempty"`
	HeroListInfo       *HeroListInfo       `protobuf:"bytes,5,req,name=hero_list_info" json:"hero_list_info,omitempty"`
	AllSoldiers        *AllSoldiers        `protobuf:"bytes,6,req,name=all_soldiers" json:"all_soldiers,omitempty"`
	BuildingInfo       *BuildingListInfo   `protobuf:"bytes,7,req,name=building_info" json:"building_info,omitempty"`
	DecorationListInfo *DecorationListInfo `protobuf:"bytes,8,req,name=decoration_list_info" json:"decoration_list_info,omitempty"`
	KingInfo           *KingInfo           `protobuf:"bytes,9,req,name=king_info" json:"king_info,omitempty"`
	MapInfo            *MapInfo            `protobuf:"bytes,10,req,name=map_info" json:"map_info,omitempty"`
	PvpHeroList        []int64             `protobuf:"varint,11,rep,name=pvp_hero_list" json:"pvp_hero_list,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *MsgLoginInRet) Reset()         { *m = MsgLoginInRet{} }
func (m *MsgLoginInRet) String() string { return proto.CompactTextString(m) }
func (*MsgLoginInRet) ProtoMessage()    {}

func (m *MsgLoginInRet) GetSystemTime() int64 {
	if m != nil && m.SystemTime != nil {
		return *m.SystemTime
	}
	return 0
}

func (m *MsgLoginInRet) GetRoleInfo() *RoleBaseInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetItemListInfo() *ItemListInfo {
	if m != nil {
		return m.ItemListInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetHeroCreateInfo() *HeroCreateInfo {
	if m != nil {
		return m.HeroCreateInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetHeroListInfo() *HeroListInfo {
	if m != nil {
		return m.HeroListInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetAllSoldiers() *AllSoldiers {
	if m != nil {
		return m.AllSoldiers
	}
	return nil
}

func (m *MsgLoginInRet) GetBuildingInfo() *BuildingListInfo {
	if m != nil {
		return m.BuildingInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetDecorationListInfo() *DecorationListInfo {
	if m != nil {
		return m.DecorationListInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetKingInfo() *KingInfo {
	if m != nil {
		return m.KingInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetMapInfo() *MapInfo {
	if m != nil {
		return m.MapInfo
	}
	return nil
}

func (m *MsgLoginInRet) GetPvpHeroList() []int64 {
	if m != nil {
		return m.PvpHeroList
	}
	return nil
}

func (m *MsgLoginInRet) SetSystemTime(value int64) {
	if m != nil {
		if m.SystemTime != nil {
			*m.SystemTime = value
			return
		}
		m.SystemTime = proto.Int64(value)
	}
}

func (m *MsgLoginInRet) SetRoleInfo(value *RoleBaseInfo) {
	if m != nil {
		m.RoleInfo = value
	}
}

func (m *MsgLoginInRet) SetItemListInfo(value *ItemListInfo) {
	if m != nil {
		m.ItemListInfo = value
	}
}

func (m *MsgLoginInRet) SetHeroCreateInfo(value *HeroCreateInfo) {
	if m != nil {
		m.HeroCreateInfo = value
	}
}

func (m *MsgLoginInRet) SetHeroListInfo(value *HeroListInfo) {
	if m != nil {
		m.HeroListInfo = value
	}
}

func (m *MsgLoginInRet) SetAllSoldiers(value *AllSoldiers) {
	if m != nil {
		m.AllSoldiers = value
	}
}

func (m *MsgLoginInRet) SetBuildingInfo(value *BuildingListInfo) {
	if m != nil {
		m.BuildingInfo = value
	}
}

func (m *MsgLoginInRet) SetDecorationListInfo(value *DecorationListInfo) {
	if m != nil {
		m.DecorationListInfo = value
	}
}

func (m *MsgLoginInRet) SetKingInfo(value *KingInfo) {
	if m != nil {
		m.KingInfo = value
	}
}

func (m *MsgLoginInRet) SetMapInfo(value *MapInfo) {
	if m != nil {
		m.MapInfo = value
	}
}

func (m *MsgLoginInRet) SetPvpHeroList(value []int64) {
	if m != nil {
		m.PvpHeroList = value
	}
}

func init() {
}
