// Code generated by protoc-gen-go.
// source: soldier.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 魔物数据
type Soldier struct {
	SchemeId          *int32        `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Level             *int32        `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Stage             *int32        `protobuf:"varint,3,req,name=stage" json:"stage,omitempty"`
	SkillLevel        []*SkillLevel `protobuf:"bytes,4,rep,name=skillLevel" json:"skillLevel,omitempty"`
	Num               *int32        `protobuf:"varint,5,req,name=num" json:"num,omitempty"`
	Exp               *int32        `protobuf:"varint,6,req,name=exp" json:"exp,omitempty"`
	Timestamp         *int64        `protobuf:"varint,7,req,name=timestamp" json:"timestamp,omitempty"`
	EvoSpeedTimeStamp *int64        `protobuf:"varint,8,req,name=evoSpeedTimeStamp" json:"evoSpeedTimeStamp,omitempty"`
	Active            *int32        `protobuf:"varint,9,req,name=active" json:"active,omitempty"`
	AutoId            *int64        `protobuf:"varint,10,req,name=autoId" json:"autoId,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *Soldier) Reset()         { *m = Soldier{} }
func (m *Soldier) String() string { return proto.CompactTextString(m) }
func (*Soldier) ProtoMessage()    {}

func (m *Soldier) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *Soldier) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Soldier) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *Soldier) GetSkillLevel() []*SkillLevel {
	if m != nil {
		return m.SkillLevel
	}
	return nil
}

func (m *Soldier) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *Soldier) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Soldier) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Soldier) GetEvoSpeedTimeStamp() int64 {
	if m != nil && m.EvoSpeedTimeStamp != nil {
		return *m.EvoSpeedTimeStamp
	}
	return 0
}

func (m *Soldier) GetActive() int32 {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return 0
}

func (m *Soldier) GetAutoId() int64 {
	if m != nil && m.AutoId != nil {
		return *m.AutoId
	}
	return 0
}

func (m *Soldier) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *Soldier) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *Soldier) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

func (m *Soldier) SetSkillLevel(value []*SkillLevel) {
	if m != nil {
		m.SkillLevel = value
	}
}

func (m *Soldier) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

func (m *Soldier) SetExp(value int32) {
	if m != nil {
		if m.Exp != nil {
			*m.Exp = value
			return
		}
		m.Exp = proto.Int32(value)
	}
}

func (m *Soldier) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *Soldier) SetEvoSpeedTimeStamp(value int64) {
	if m != nil {
		if m.EvoSpeedTimeStamp != nil {
			*m.EvoSpeedTimeStamp = value
			return
		}
		m.EvoSpeedTimeStamp = proto.Int64(value)
	}
}

func (m *Soldier) SetActive(value int32) {
	if m != nil {
		if m.Active != nil {
			*m.Active = value
			return
		}
		m.Active = proto.Int32(value)
	}
}

func (m *Soldier) SetAutoId(value int64) {
	if m != nil {
		if m.AutoId != nil {
			*m.AutoId = value
			return
		}
		m.AutoId = proto.Int64(value)
	}
}

type SkillLevel struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	SkillLevel       *int32 `protobuf:"varint,2,req,name=skillLevel" json:"skillLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SkillLevel) Reset()         { *m = SkillLevel{} }
func (m *SkillLevel) String() string { return proto.CompactTextString(m) }
func (*SkillLevel) ProtoMessage()    {}

func (m *SkillLevel) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SkillLevel) GetSkillLevel() int32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *SkillLevel) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *SkillLevel) SetSkillLevel(value int32) {
	if m != nil {
		if m.SkillLevel != nil {
			*m.SkillLevel = value
			return
		}
		m.SkillLevel = proto.Int32(value)
	}
}

type LostSoldier struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Num              *int32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LostSoldier) Reset()         { *m = LostSoldier{} }
func (m *LostSoldier) String() string { return proto.CompactTextString(m) }
func (*LostSoldier) ProtoMessage()    {}

func (m *LostSoldier) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *LostSoldier) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *LostSoldier) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *LostSoldier) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

// all
type AllSoldiers struct {
	SoldiersInCamp   []*Soldier `protobuf:"bytes,1,rep,name=soldiersInCamp" json:"soldiersInCamp,omitempty"`
	SoldiersInMap    []*Soldier `protobuf:"bytes,2,rep,name=soldiersInMap" json:"soldiersInMap,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AllSoldiers) Reset()         { *m = AllSoldiers{} }
func (m *AllSoldiers) String() string { return proto.CompactTextString(m) }
func (*AllSoldiers) ProtoMessage()    {}

func (m *AllSoldiers) GetSoldiersInCamp() []*Soldier {
	if m != nil {
		return m.SoldiersInCamp
	}
	return nil
}

func (m *AllSoldiers) GetSoldiersInMap() []*Soldier {
	if m != nil {
		return m.SoldiersInMap
	}
	return nil
}

func (m *AllSoldiers) SetSoldiersInCamp(value []*Soldier) {
	if m != nil {
		m.SoldiersInCamp = value
	}
}

func (m *AllSoldiers) SetSoldiersInMap(value []*Soldier) {
	if m != nil {
		m.SoldiersInMap = value
	}
}

type MsgSoldierAllReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierAllReq) Reset()         { *m = MsgSoldierAllReq{} }
func (m *MsgSoldierAllReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierAllReq) ProtoMessage()    {}

type MsgSoldierAllRet struct {
	SoldiersInCamp   []*Soldier `protobuf:"bytes,1,rep,name=soldiersInCamp" json:"soldiersInCamp,omitempty"`
	SoldiersInMap    []*Soldier `protobuf:"bytes,2,rep,name=soldiersInMap" json:"soldiersInMap,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MsgSoldierAllRet) Reset()         { *m = MsgSoldierAllRet{} }
func (m *MsgSoldierAllRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierAllRet) ProtoMessage()    {}

func (m *MsgSoldierAllRet) GetSoldiersInCamp() []*Soldier {
	if m != nil {
		return m.SoldiersInCamp
	}
	return nil
}

func (m *MsgSoldierAllRet) GetSoldiersInMap() []*Soldier {
	if m != nil {
		return m.SoldiersInMap
	}
	return nil
}

func (m *MsgSoldierAllRet) SetSoldiersInCamp(value []*Soldier) {
	if m != nil {
		m.SoldiersInCamp = value
	}
}

func (m *MsgSoldierAllRet) SetSoldiersInMap(value []*Soldier) {
	if m != nil {
		m.SoldiersInMap = value
	}
}

// 變更通知
type MsgSoldierNotify struct {
	Soldier          *Soldier `protobuf:"bytes,1,req,name=soldier" json:"soldier,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgSoldierNotify) Reset()         { *m = MsgSoldierNotify{} }
func (m *MsgSoldierNotify) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierNotify) ProtoMessage()    {}

func (m *MsgSoldierNotify) GetSoldier() *Soldier {
	if m != nil {
		return m.Soldier
	}
	return nil
}

func (m *MsgSoldierNotify) SetSoldier(value *Soldier) {
	if m != nil {
		m.Soldier = value
	}
}

// 魔物合成
type MsgSoldierCreateReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	Amount           *int32 `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierCreateReq) Reset()         { *m = MsgSoldierCreateReq{} }
func (m *MsgSoldierCreateReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierCreateReq) ProtoMessage()    {}

func (m *MsgSoldierCreateReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierCreateReq) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *MsgSoldierCreateReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierCreateReq) SetAmount(value int32) {
	if m != nil {
		if m.Amount != nil {
			*m.Amount = value
			return
		}
		m.Amount = proto.Int32(value)
	}
}

// 创建
type MsgSoldierCreateRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	SoldierId        *int32 `protobuf:"varint,2,req,name=soldierId" json:"soldierId,omitempty"`
	Amount           *int32 `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierCreateRet) Reset()         { *m = MsgSoldierCreateRet{} }
func (m *MsgSoldierCreateRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierCreateRet) ProtoMessage()    {}

func (m *MsgSoldierCreateRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierCreateRet) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierCreateRet) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *MsgSoldierCreateRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierCreateRet) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierCreateRet) SetAmount(value int32) {
	if m != nil {
		if m.Amount != nil {
			*m.Amount = value
			return
		}
		m.Amount = proto.Int32(value)
	}
}

// 升级
type MsgSoldierLvRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,3,req,name=exp" json:"exp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierLvRet) Reset()         { *m = MsgSoldierLvRet{} }
func (m *MsgSoldierLvRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierLvRet) ProtoMessage()    {}

func (m *MsgSoldierLvRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierLvRet) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MsgSoldierLvRet) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *MsgSoldierLvRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierLvRet) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *MsgSoldierLvRet) SetExp(value int32) {
	if m != nil {
		if m.Exp != nil {
			*m.Exp = value
			return
		}
		m.Exp = proto.Int32(value)
	}
}

// 魔物进阶
type MsgSoldierUpgradeReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	HeroId           *int64 `protobuf:"varint,2,req,name=heroId" json:"heroId,omitempty"`
	UsedCoin         *bool  `protobuf:"varint,3,req,name=usedCoin" json:"usedCoin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierUpgradeReq) Reset()         { *m = MsgSoldierUpgradeReq{} }
func (m *MsgSoldierUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierUpgradeReq) ProtoMessage()    {}

func (m *MsgSoldierUpgradeReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierUpgradeReq) GetHeroId() int64 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *MsgSoldierUpgradeReq) GetUsedCoin() bool {
	if m != nil && m.UsedCoin != nil {
		return *m.UsedCoin
	}
	return false
}

func (m *MsgSoldierUpgradeReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierUpgradeReq) SetHeroId(value int64) {
	if m != nil {
		if m.HeroId != nil {
			*m.HeroId = value
			return
		}
		m.HeroId = proto.Int64(value)
	}
}

func (m *MsgSoldierUpgradeReq) SetUsedCoin(value bool) {
	if m != nil {
		if m.UsedCoin != nil {
			*m.UsedCoin = value
			return
		}
		m.UsedCoin = proto.Bool(value)
	}
}

type MsgSoldierUpgradeRet struct {
	RetCode           *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	Timestamp         *int64 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	EvoSpeedTimeStamp *int64 `protobuf:"varint,3,req,name=evoSpeedTimeStamp" json:"evoSpeedTimeStamp,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *MsgSoldierUpgradeRet) Reset()         { *m = MsgSoldierUpgradeRet{} }
func (m *MsgSoldierUpgradeRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierUpgradeRet) ProtoMessage()    {}

func (m *MsgSoldierUpgradeRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierUpgradeRet) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *MsgSoldierUpgradeRet) GetEvoSpeedTimeStamp() int64 {
	if m != nil && m.EvoSpeedTimeStamp != nil {
		return *m.EvoSpeedTimeStamp
	}
	return 0
}

func (m *MsgSoldierUpgradeRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierUpgradeRet) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *MsgSoldierUpgradeRet) SetEvoSpeedTimeStamp(value int64) {
	if m != nil {
		if m.EvoSpeedTimeStamp != nil {
			*m.EvoSpeedTimeStamp = value
			return
		}
		m.EvoSpeedTimeStamp = proto.Int64(value)
	}
}

// 使用货币移除升级时间，马上升级
type MsgSoldierRemoveUpgradeTimeReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierRemoveUpgradeTimeReq) Reset()         { *m = MsgSoldierRemoveUpgradeTimeReq{} }
func (m *MsgSoldierRemoveUpgradeTimeReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierRemoveUpgradeTimeReq) ProtoMessage()    {}

func (m *MsgSoldierRemoveUpgradeTimeReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierRemoveUpgradeTimeReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

type MsgSoldierRemoveUpgradeTimeRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierRemoveUpgradeTimeRet) Reset()         { *m = MsgSoldierRemoveUpgradeTimeRet{} }
func (m *MsgSoldierRemoveUpgradeTimeRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierRemoveUpgradeTimeRet) ProtoMessage()    {}

func (m *MsgSoldierRemoveUpgradeTimeRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierRemoveUpgradeTimeRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 魔物进阶加速
type MsgSoldierCutDownUpgradeTimeReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierCutDownUpgradeTimeReq) Reset()         { *m = MsgSoldierCutDownUpgradeTimeReq{} }
func (m *MsgSoldierCutDownUpgradeTimeReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierCutDownUpgradeTimeReq) ProtoMessage()    {}

func (m *MsgSoldierCutDownUpgradeTimeReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierCutDownUpgradeTimeReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

type MsgSoldierCutDownUpgradeTimeRet struct {
	RetCode           *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	EvoSpeedTimeStamp *int64 `protobuf:"varint,2,opt,name=evoSpeedTimeStamp" json:"evoSpeedTimeStamp,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *MsgSoldierCutDownUpgradeTimeRet) Reset()         { *m = MsgSoldierCutDownUpgradeTimeRet{} }
func (m *MsgSoldierCutDownUpgradeTimeRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierCutDownUpgradeTimeRet) ProtoMessage()    {}

func (m *MsgSoldierCutDownUpgradeTimeRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierCutDownUpgradeTimeRet) GetEvoSpeedTimeStamp() int64 {
	if m != nil && m.EvoSpeedTimeStamp != nil {
		return *m.EvoSpeedTimeStamp
	}
	return 0
}

func (m *MsgSoldierCutDownUpgradeTimeRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierCutDownUpgradeTimeRet) SetEvoSpeedTimeStamp(value int64) {
	if m != nil {
		if m.EvoSpeedTimeStamp != nil {
			*m.EvoSpeedTimeStamp = value
			return
		}
		m.EvoSpeedTimeStamp = proto.Int64(value)
	}
}

// 检查是否完成升階
type MsgSoldierFinishUpgradeReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierFinishUpgradeReq) Reset()         { *m = MsgSoldierFinishUpgradeReq{} }
func (m *MsgSoldierFinishUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierFinishUpgradeReq) ProtoMessage()    {}

func (m *MsgSoldierFinishUpgradeReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierFinishUpgradeReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

type MsgSoldierFinishUpgradeRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	SoldierId        *int32 `protobuf:"varint,2,req,name=soldierId" json:"soldierId,omitempty"`
	Stage            *int32 `protobuf:"varint,3,req,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierFinishUpgradeRet) Reset()         { *m = MsgSoldierFinishUpgradeRet{} }
func (m *MsgSoldierFinishUpgradeRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierFinishUpgradeRet) ProtoMessage()    {}

func (m *MsgSoldierFinishUpgradeRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierFinishUpgradeRet) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierFinishUpgradeRet) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *MsgSoldierFinishUpgradeRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierFinishUpgradeRet) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierFinishUpgradeRet) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

// 魔物技能强化请求
type MsgSoldierSkillLvReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	SkillId          *int32 `protobuf:"varint,2,req,name=skillId" json:"skillId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierSkillLvReq) Reset()         { *m = MsgSoldierSkillLvReq{} }
func (m *MsgSoldierSkillLvReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierSkillLvReq) ProtoMessage()    {}

func (m *MsgSoldierSkillLvReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierSkillLvReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgSoldierSkillLvReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierSkillLvReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

type MsgSoldierSkillLvRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierSkillLvRet) Reset()         { *m = MsgSoldierSkillLvRet{} }
func (m *MsgSoldierSkillLvRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierSkillLvRet) ProtoMessage()    {}

func (m *MsgSoldierSkillLvRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierSkillLvRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 地图事件
type SoldierEvent struct {
	EventId          *int32 `protobuf:"varint,1,req,name=eventId" json:"eventId,omitempty"`
	StartTime        *int64 `protobuf:"varint,2,req,name=startTime" json:"startTime,omitempty"`
	EndTime          *int64 `protobuf:"varint,3,req,name=endTime" json:"endTime,omitempty"`
	Duration         *int64 `protobuf:"varint,4,req,name=duration" json:"duration,omitempty"`
	EventType        *int32 `protobuf:"varint,5,req,name=eventType" json:"eventType,omitempty"`
	Remote           *int32 `protobuf:"varint,6,req,name=remote" json:"remote,omitempty"`
	Local            *int32 `protobuf:"varint,7,req,name=local" json:"local,omitempty"`
	LevelTotal       *int32 `protobuf:"varint,8,opt,name=levelTotal" json:"levelTotal,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SoldierEvent) Reset()         { *m = SoldierEvent{} }
func (m *SoldierEvent) String() string { return proto.CompactTextString(m) }
func (*SoldierEvent) ProtoMessage()    {}

func (m *SoldierEvent) GetEventId() int32 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *SoldierEvent) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *SoldierEvent) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *SoldierEvent) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *SoldierEvent) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *SoldierEvent) GetRemote() int32 {
	if m != nil && m.Remote != nil {
		return *m.Remote
	}
	return 0
}

func (m *SoldierEvent) GetLocal() int32 {
	if m != nil && m.Local != nil {
		return *m.Local
	}
	return 0
}

func (m *SoldierEvent) GetLevelTotal() int32 {
	if m != nil && m.LevelTotal != nil {
		return *m.LevelTotal
	}
	return 0
}

func (m *SoldierEvent) SetEventId(value int32) {
	if m != nil {
		if m.EventId != nil {
			*m.EventId = value
			return
		}
		m.EventId = proto.Int32(value)
	}
}

func (m *SoldierEvent) SetStartTime(value int64) {
	if m != nil {
		if m.StartTime != nil {
			*m.StartTime = value
			return
		}
		m.StartTime = proto.Int64(value)
	}
}

func (m *SoldierEvent) SetEndTime(value int64) {
	if m != nil {
		if m.EndTime != nil {
			*m.EndTime = value
			return
		}
		m.EndTime = proto.Int64(value)
	}
}

func (m *SoldierEvent) SetDuration(value int64) {
	if m != nil {
		if m.Duration != nil {
			*m.Duration = value
			return
		}
		m.Duration = proto.Int64(value)
	}
}

func (m *SoldierEvent) SetEventType(value int32) {
	if m != nil {
		if m.EventType != nil {
			*m.EventType = value
			return
		}
		m.EventType = proto.Int32(value)
	}
}

func (m *SoldierEvent) SetRemote(value int32) {
	if m != nil {
		if m.Remote != nil {
			*m.Remote = value
			return
		}
		m.Remote = proto.Int32(value)
	}
}

func (m *SoldierEvent) SetLocal(value int32) {
	if m != nil {
		if m.Local != nil {
			*m.Local = value
			return
		}
		m.Local = proto.Int32(value)
	}
}

func (m *SoldierEvent) SetLevelTotal(value int32) {
	if m != nil {
		if m.LevelTotal != nil {
			*m.LevelTotal = value
			return
		}
		m.LevelTotal = proto.Int32(value)
	}
}

// 事件
type AllSoldiersEvents struct {
	Events1          []*SoldierEvent `protobuf:"bytes,1,rep,name=events1" json:"events1,omitempty"`
	Events2          []*SoldierEvent `protobuf:"bytes,2,rep,name=events2" json:"events2,omitempty"`
	Events3          []*SoldierEvent `protobuf:"bytes,3,rep,name=events3" json:"events3,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *AllSoldiersEvents) Reset()         { *m = AllSoldiersEvents{} }
func (m *AllSoldiersEvents) String() string { return proto.CompactTextString(m) }
func (*AllSoldiersEvents) ProtoMessage()    {}

func (m *AllSoldiersEvents) GetEvents1() []*SoldierEvent {
	if m != nil {
		return m.Events1
	}
	return nil
}

func (m *AllSoldiersEvents) GetEvents2() []*SoldierEvent {
	if m != nil {
		return m.Events2
	}
	return nil
}

func (m *AllSoldiersEvents) GetEvents3() []*SoldierEvent {
	if m != nil {
		return m.Events3
	}
	return nil
}

func (m *AllSoldiersEvents) SetEvents1(value []*SoldierEvent) {
	if m != nil {
		m.Events1 = value
	}
}

func (m *AllSoldiersEvents) SetEvents2(value []*SoldierEvent) {
	if m != nil {
		m.Events2 = value
	}
}

func (m *AllSoldiersEvents) SetEvents3(value []*SoldierEvent) {
	if m != nil {
		m.Events3 = value
	}
}

// 所有事件
type MsgSoldierAllEventsReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierAllEventsReq) Reset()         { *m = MsgSoldierAllEventsReq{} }
func (m *MsgSoldierAllEventsReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierAllEventsReq) ProtoMessage()    {}

type MsgSoldierAllEventsRet struct {
	AllEvents        *AllSoldiersEvents `protobuf:"bytes,1,req,name=allEvents" json:"allEvents,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MsgSoldierAllEventsRet) Reset()         { *m = MsgSoldierAllEventsRet{} }
func (m *MsgSoldierAllEventsRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierAllEventsRet) ProtoMessage()    {}

func (m *MsgSoldierAllEventsRet) GetAllEvents() *AllSoldiersEvents {
	if m != nil {
		return m.AllEvents
	}
	return nil
}

func (m *MsgSoldierAllEventsRet) SetAllEvents(value *AllSoldiersEvents) {
	if m != nil {
		m.AllEvents = value
	}
}

// 处理地图事件
type MsgSoldierEventDealWithReq struct {
	EventType        *int32 `protobuf:"varint,1,req,name=eventType" json:"eventType,omitempty"`
	EventId          *int32 `protobuf:"varint,2,req,name=eventId" json:"eventId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierEventDealWithReq) Reset()         { *m = MsgSoldierEventDealWithReq{} }
func (m *MsgSoldierEventDealWithReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierEventDealWithReq) ProtoMessage()    {}

func (m *MsgSoldierEventDealWithReq) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *MsgSoldierEventDealWithReq) GetEventId() int32 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *MsgSoldierEventDealWithReq) SetEventType(value int32) {
	if m != nil {
		if m.EventType != nil {
			*m.EventType = value
			return
		}
		m.EventType = proto.Int32(value)
	}
}

func (m *MsgSoldierEventDealWithReq) SetEventId(value int32) {
	if m != nil {
		if m.EventId != nil {
			*m.EventId = value
			return
		}
		m.EventId = proto.Int32(value)
	}
}

type MsgSoldierEventDealWithRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierEventDealWithRet) Reset()         { *m = MsgSoldierEventDealWithRet{} }
func (m *MsgSoldierEventDealWithRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierEventDealWithRet) ProtoMessage()    {}

func (m *MsgSoldierEventDealWithRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierEventDealWithRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func init() {
}
