// Code generated by protoc-gen-go.
// source: map.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MapGridInfo struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	BaseType         *int32 `protobuf:"varint,3,req,name=base_type" json:"base_type,omitempty"`
	ObjType          *int32 `protobuf:"varint,4,req,name=obj_type" json:"obj_type,omitempty"`
	Id               *int64 `protobuf:"varint,5,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MapGridInfo) Reset()         { *m = MapGridInfo{} }
func (m *MapGridInfo) String() string { return proto.CompactTextString(m) }
func (*MapGridInfo) ProtoMessage()    {}

func (m *MapGridInfo) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MapGridInfo) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MapGridInfo) GetBaseType() int32 {
	if m != nil && m.BaseType != nil {
		return *m.BaseType
	}
	return 0
}

func (m *MapGridInfo) GetObjType() int32 {
	if m != nil && m.ObjType != nil {
		return *m.ObjType
	}
	return 0
}

func (m *MapGridInfo) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MapGridInfo) SetX(value int32) {
	if m != nil {
		if m.X != nil {
			*m.X = value
			return
		}
		m.X = proto.Int32(value)
	}
}

func (m *MapGridInfo) SetY(value int32) {
	if m != nil {
		if m.Y != nil {
			*m.Y = value
			return
		}
		m.Y = proto.Int32(value)
	}
}

func (m *MapGridInfo) SetBaseType(value int32) {
	if m != nil {
		if m.BaseType != nil {
			*m.BaseType = value
			return
		}
		m.BaseType = proto.Int32(value)
	}
}

func (m *MapGridInfo) SetObjType(value int32) {
	if m != nil {
		if m.ObjType != nil {
			*m.ObjType = value
			return
		}
		m.ObjType = proto.Int32(value)
	}
}

func (m *MapGridInfo) SetId(value int64) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int64(value)
	}
}

type MapInfo struct {
	MapInfos         []*MapGridInfo `protobuf:"bytes,1,rep,name=map_infos" json:"map_infos,omitempty"`
	MapPointList     []int32        `protobuf:"varint,2,rep,name=map_point_list" json:"map_point_list,omitempty"`
	MapPointActive   []int32        `protobuf:"varint,3,rep,name=map_point_active" json:"map_point_active,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MapInfo) Reset()         { *m = MapInfo{} }
func (m *MapInfo) String() string { return proto.CompactTextString(m) }
func (*MapInfo) ProtoMessage()    {}

func (m *MapInfo) GetMapInfos() []*MapGridInfo {
	if m != nil {
		return m.MapInfos
	}
	return nil
}

func (m *MapInfo) GetMapPointList() []int32 {
	if m != nil {
		return m.MapPointList
	}
	return nil
}

func (m *MapInfo) GetMapPointActive() []int32 {
	if m != nil {
		return m.MapPointActive
	}
	return nil
}

func (m *MapInfo) SetMapInfos(value []*MapGridInfo) {
	if m != nil {
		m.MapInfos = value
	}
}

func (m *MapInfo) SetMapPointList(value []int32) {
	if m != nil {
		m.MapPointList = value
	}
}

func (m *MapInfo) SetMapPointActive(value []int32) {
	if m != nil {
		m.MapPointActive = value
	}
}

type MsgMapRefreshReq struct {
	MapInfos         []*MapGridInfo `protobuf:"bytes,1,rep,name=map_infos" json:"map_infos,omitempty"`
	MapPointActive   []int32        `protobuf:"varint,2,rep,name=map_point_active" json:"map_point_active,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgMapRefreshReq) Reset()         { *m = MsgMapRefreshReq{} }
func (m *MsgMapRefreshReq) String() string { return proto.CompactTextString(m) }
func (*MsgMapRefreshReq) ProtoMessage()    {}

func (m *MsgMapRefreshReq) GetMapInfos() []*MapGridInfo {
	if m != nil {
		return m.MapInfos
	}
	return nil
}

func (m *MsgMapRefreshReq) GetMapPointActive() []int32 {
	if m != nil {
		return m.MapPointActive
	}
	return nil
}

func (m *MsgMapRefreshReq) SetMapInfos(value []*MapGridInfo) {
	if m != nil {
		m.MapInfos = value
	}
}

func (m *MsgMapRefreshReq) SetMapPointActive(value []int32) {
	if m != nil {
		m.MapPointActive = value
	}
}

type MsgMapRefreshRet struct {
	Retcode          *int32 `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMapRefreshRet) Reset()         { *m = MsgMapRefreshRet{} }
func (m *MsgMapRefreshRet) String() string { return proto.CompactTextString(m) }
func (*MsgMapRefreshRet) ProtoMessage()    {}

func (m *MsgMapRefreshRet) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *MsgMapRefreshRet) SetRetcode(value int32) {
	if m != nil {
		if m.Retcode != nil {
			*m.Retcode = value
			return
		}
		m.Retcode = proto.Int32(value)
	}
}

type MsgMapUpdateNotify struct {
	MapInfos         []*MapGridInfo `protobuf:"bytes,1,rep,name=map_infos" json:"map_infos,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgMapUpdateNotify) Reset()         { *m = MsgMapUpdateNotify{} }
func (m *MsgMapUpdateNotify) String() string { return proto.CompactTextString(m) }
func (*MsgMapUpdateNotify) ProtoMessage()    {}

func (m *MsgMapUpdateNotify) GetMapInfos() []*MapGridInfo {
	if m != nil {
		return m.MapInfos
	}
	return nil
}

func (m *MsgMapUpdateNotify) SetMapInfos(value []*MapGridInfo) {
	if m != nil {
		m.MapInfos = value
	}
}

type MsgMapUpdatePointNotify struct {
	MapInfo          *MapGridInfo `protobuf:"bytes,1,req,name=map_info" json:"map_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgMapUpdatePointNotify) Reset()         { *m = MsgMapUpdatePointNotify{} }
func (m *MsgMapUpdatePointNotify) String() string { return proto.CompactTextString(m) }
func (*MsgMapUpdatePointNotify) ProtoMessage()    {}

func (m *MsgMapUpdatePointNotify) GetMapInfo() *MapGridInfo {
	if m != nil {
		return m.MapInfo
	}
	return nil
}

func (m *MsgMapUpdatePointNotify) SetMapInfo(value *MapGridInfo) {
	if m != nil {
		m.MapInfo = value
	}
}

type MsgMapRemoveObstacleReq struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=scheme_id" json:"scheme_id,omitempty"`
	PosX             *int32 `protobuf:"varint,2,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *int32 `protobuf:"varint,3,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMapRemoveObstacleReq) Reset()         { *m = MsgMapRemoveObstacleReq{} }
func (m *MsgMapRemoveObstacleReq) String() string { return proto.CompactTextString(m) }
func (*MsgMapRemoveObstacleReq) ProtoMessage()    {}

func (m *MsgMapRemoveObstacleReq) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgMapRemoveObstacleReq) GetPosX() int32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *MsgMapRemoveObstacleReq) GetPosY() int32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *MsgMapRemoveObstacleReq) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgMapRemoveObstacleReq) SetPosX(value int32) {
	if m != nil {
		if m.PosX != nil {
			*m.PosX = value
			return
		}
		m.PosX = proto.Int32(value)
	}
}

func (m *MsgMapRemoveObstacleReq) SetPosY(value int32) {
	if m != nil {
		if m.PosY != nil {
			*m.PosY = value
			return
		}
		m.PosY = proto.Int32(value)
	}
}

type MsgMapRemoveObstacleRet struct {
	Retcode          *int32 `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMapRemoveObstacleRet) Reset()         { *m = MsgMapRemoveObstacleRet{} }
func (m *MsgMapRemoveObstacleRet) String() string { return proto.CompactTextString(m) }
func (*MsgMapRemoveObstacleRet) ProtoMessage()    {}

func (m *MsgMapRemoveObstacleRet) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *MsgMapRemoveObstacleRet) SetRetcode(value int32) {
	if m != nil {
		if m.Retcode != nil {
			*m.Retcode = value
			return
		}
		m.Retcode = proto.Int32(value)
	}
}

type MsgMapUnLockPointReq struct {
	PointId          *int32 `protobuf:"varint,1,req,name=point_id" json:"point_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMapUnLockPointReq) Reset()         { *m = MsgMapUnLockPointReq{} }
func (m *MsgMapUnLockPointReq) String() string { return proto.CompactTextString(m) }
func (*MsgMapUnLockPointReq) ProtoMessage()    {}

func (m *MsgMapUnLockPointReq) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}

func (m *MsgMapUnLockPointReq) SetPointId(value int32) {
	if m != nil {
		if m.PointId != nil {
			*m.PointId = value
			return
		}
		m.PointId = proto.Int32(value)
	}
}

type MsgMapUnLockPointRet struct {
	Retcode          *int32 `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	PointId          *int32 `protobuf:"varint,2,req,name=point_id" json:"point_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMapUnLockPointRet) Reset()         { *m = MsgMapUnLockPointRet{} }
func (m *MsgMapUnLockPointRet) String() string { return proto.CompactTextString(m) }
func (*MsgMapUnLockPointRet) ProtoMessage()    {}

func (m *MsgMapUnLockPointRet) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *MsgMapUnLockPointRet) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}

func (m *MsgMapUnLockPointRet) SetRetcode(value int32) {
	if m != nil {
		if m.Retcode != nil {
			*m.Retcode = value
			return
		}
		m.Retcode = proto.Int32(value)
	}
}

func (m *MsgMapUnLockPointRet) SetPointId(value int32) {
	if m != nil {
		if m.PointId != nil {
			*m.PointId = value
			return
		}
		m.PointId = proto.Int32(value)
	}
}

func init() {
}
