// Code generated by protoc-gen-go.
// source: mission.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Mission struct {
	SchemeId         *int32          `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	ReachedNum       *int32          `protobuf:"varint,2,req,name=reachedNum" json:"reachedNum,omitempty"`
	TargetNum        *int32          `protobuf:"varint,3,req,name=targetNum" json:"targetNum,omitempty"`
	Timestamp        *int64          `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	Finished         *bool           `protobuf:"varint,5,req,name=finished" json:"finished,omitempty"`
	Level            *int32          `protobuf:"varint,6,req,name=level" json:"level,omitempty"`
	Awards           []*MissionAward `protobuf:"bytes,7,rep,name=awards" json:"awards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Mission) Reset()         { *m = Mission{} }
func (m *Mission) String() string { return proto.CompactTextString(m) }
func (*Mission) ProtoMessage()    {}

func (m *Mission) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *Mission) GetReachedNum() int32 {
	if m != nil && m.ReachedNum != nil {
		return *m.ReachedNum
	}
	return 0
}

func (m *Mission) GetTargetNum() int32 {
	if m != nil && m.TargetNum != nil {
		return *m.TargetNum
	}
	return 0
}

func (m *Mission) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Mission) GetFinished() bool {
	if m != nil && m.Finished != nil {
		return *m.Finished
	}
	return false
}

func (m *Mission) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Mission) GetAwards() []*MissionAward {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *Mission) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *Mission) SetReachedNum(value int32) {
	if m != nil {
		if m.ReachedNum != nil {
			*m.ReachedNum = value
			return
		}
		m.ReachedNum = proto.Int32(value)
	}
}

func (m *Mission) SetTargetNum(value int32) {
	if m != nil {
		if m.TargetNum != nil {
			*m.TargetNum = value
			return
		}
		m.TargetNum = proto.Int32(value)
	}
}

func (m *Mission) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *Mission) SetFinished(value bool) {
	if m != nil {
		if m.Finished != nil {
			*m.Finished = value
			return
		}
		m.Finished = proto.Bool(value)
	}
}

func (m *Mission) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *Mission) SetAwards(value []*MissionAward) {
	if m != nil {
		m.Awards = value
	}
}

type MissionAward struct {
	AwardId          *int32 `protobuf:"varint,1,req,name=awardId" json:"awardId,omitempty"`
	LvParam          *int32 `protobuf:"varint,2,req,name=lvParam" json:"lvParam,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MissionAward) Reset()         { *m = MissionAward{} }
func (m *MissionAward) String() string { return proto.CompactTextString(m) }
func (*MissionAward) ProtoMessage()    {}

func (m *MissionAward) GetAwardId() int32 {
	if m != nil && m.AwardId != nil {
		return *m.AwardId
	}
	return 0
}

func (m *MissionAward) GetLvParam() int32 {
	if m != nil && m.LvParam != nil {
		return *m.LvParam
	}
	return 0
}

func (m *MissionAward) SetAwardId(value int32) {
	if m != nil {
		if m.AwardId != nil {
			*m.AwardId = value
			return
		}
		m.AwardId = proto.Int32(value)
	}
}

func (m *MissionAward) SetLvParam(value int32) {
	if m != nil {
		if m.LvParam != nil {
			*m.LvParam = value
			return
		}
		m.LvParam = proto.Int32(value)
	}
}

type MsgMissionAllReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMissionAllReq) Reset()         { *m = MsgMissionAllReq{} }
func (m *MsgMissionAllReq) String() string { return proto.CompactTextString(m) }
func (*MsgMissionAllReq) ProtoMessage()    {}

type MsgMissionAllRet struct {
	Missions         []*Mission `protobuf:"bytes,1,rep,name=missions" json:"missions,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MsgMissionAllRet) Reset()         { *m = MsgMissionAllRet{} }
func (m *MsgMissionAllRet) String() string { return proto.CompactTextString(m) }
func (*MsgMissionAllRet) ProtoMessage()    {}

func (m *MsgMissionAllRet) GetMissions() []*Mission {
	if m != nil {
		return m.Missions
	}
	return nil
}

func (m *MsgMissionAllRet) SetMissions(value []*Mission) {
	if m != nil {
		m.Missions = value
	}
}

// 增加任务目标达成的数量
type MsgMissionAddNumReq struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Num              *int32 `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	TargetLevel      *int32 `protobuf:"varint,3,req,name=targetLevel" json:"targetLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMissionAddNumReq) Reset()         { *m = MsgMissionAddNumReq{} }
func (m *MsgMissionAddNumReq) String() string { return proto.CompactTextString(m) }
func (*MsgMissionAddNumReq) ProtoMessage()    {}

func (m *MsgMissionAddNumReq) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgMissionAddNumReq) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *MsgMissionAddNumReq) GetTargetLevel() int32 {
	if m != nil && m.TargetLevel != nil {
		return *m.TargetLevel
	}
	return 0
}

func (m *MsgMissionAddNumReq) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgMissionAddNumReq) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

func (m *MsgMissionAddNumReq) SetTargetLevel(value int32) {
	if m != nil {
		if m.TargetLevel != nil {
			*m.TargetLevel = value
			return
		}
		m.TargetLevel = proto.Int32(value)
	}
}

type MsgMissionAddNumRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	ReachedNum       *int32 `protobuf:"varint,2,req,name=reachedNum" json:"reachedNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMissionAddNumRet) Reset()         { *m = MsgMissionAddNumRet{} }
func (m *MsgMissionAddNumRet) String() string { return proto.CompactTextString(m) }
func (*MsgMissionAddNumRet) ProtoMessage()    {}

func (m *MsgMissionAddNumRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgMissionAddNumRet) GetReachedNum() int32 {
	if m != nil && m.ReachedNum != nil {
		return *m.ReachedNum
	}
	return 0
}

func (m *MsgMissionAddNumRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgMissionAddNumRet) SetReachedNum(value int32) {
	if m != nil {
		if m.ReachedNum != nil {
			*m.ReachedNum = value
			return
		}
		m.ReachedNum = proto.Int32(value)
	}
}

// 完成任务
type MsgMissionFinishReq struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMissionFinishReq) Reset()         { *m = MsgMissionFinishReq{} }
func (m *MsgMissionFinishReq) String() string { return proto.CompactTextString(m) }
func (*MsgMissionFinishReq) ProtoMessage()    {}

func (m *MsgMissionFinishReq) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgMissionFinishReq) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

type MsgMissionFinishRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgMissionFinishRet) Reset()         { *m = MsgMissionFinishRet{} }
func (m *MsgMissionFinishRet) String() string { return proto.CompactTextString(m) }
func (*MsgMissionFinishRet) ProtoMessage()    {}

func (m *MsgMissionFinishRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgMissionFinishRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

// 任务达成通知
type MsgMissionNotifyRet struct {
	Mission          *Mission `protobuf:"bytes,1,req,name=mission" json:"mission,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgMissionNotifyRet) Reset()         { *m = MsgMissionNotifyRet{} }
func (m *MsgMissionNotifyRet) String() string { return proto.CompactTextString(m) }
func (*MsgMissionNotifyRet) ProtoMessage()    {}

func (m *MsgMissionNotifyRet) GetMission() *Mission {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *MsgMissionNotifyRet) SetMission(value *Mission) {
	if m != nil {
		m.Mission = value
	}
}

func init() {
}
