// Code generated by protoc-gen-go.
// source: soldier.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 魔物数据
type Soldier struct {
	SchemeId         *int32        `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Level            *int32        `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Stage            *int32        `protobuf:"varint,3,req,name=stage" json:"stage,omitempty"`
	SkillLevel       []*SkillLevel `protobuf:"bytes,4,rep,name=skillLevel" json:"skillLevel,omitempty"`
	Num              *int32        `protobuf:"varint,5,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Soldier) Reset()         { *m = Soldier{} }
func (m *Soldier) String() string { return proto.CompactTextString(m) }
func (*Soldier) ProtoMessage()    {}

func (m *Soldier) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *Soldier) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Soldier) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *Soldier) GetSkillLevel() []*SkillLevel {
	if m != nil {
		return m.SkillLevel
	}
	return nil
}

func (m *Soldier) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *Soldier) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *Soldier) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

func (m *Soldier) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

func (m *Soldier) SetSkillLevel(value []*SkillLevel) {
	if m != nil {
		m.SkillLevel = value
	}
}

func (m *Soldier) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

type SkillLevel struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	SkillLevel       *int32 `protobuf:"varint,2,req,name=skillLevel" json:"skillLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SkillLevel) Reset()         { *m = SkillLevel{} }
func (m *SkillLevel) String() string { return proto.CompactTextString(m) }
func (*SkillLevel) ProtoMessage()    {}

func (m *SkillLevel) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SkillLevel) GetSkillLevel() int32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *SkillLevel) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *SkillLevel) SetSkillLevel(value int32) {
	if m != nil {
		if m.SkillLevel != nil {
			*m.SkillLevel = value
			return
		}
		m.SkillLevel = proto.Int32(value)
	}
}

// all
type AllSoldiers struct {
	SoldiersInCamp   []*Soldier `protobuf:"bytes,1,rep,name=soldiersInCamp" json:"soldiersInCamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AllSoldiers) Reset()         { *m = AllSoldiers{} }
func (m *AllSoldiers) String() string { return proto.CompactTextString(m) }
func (*AllSoldiers) ProtoMessage()    {}

func (m *AllSoldiers) GetSoldiersInCamp() []*Soldier {
	if m != nil {
		return m.SoldiersInCamp
	}
	return nil
}

func (m *AllSoldiers) SetSoldiersInCamp(value []*Soldier) {
	if m != nil {
		m.SoldiersInCamp = value
	}
}

// 變更通知
type MsgSoldierNotify struct {
	Soldier          *Soldier `protobuf:"bytes,1,req,name=soldier" json:"soldier,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgSoldierNotify) Reset()         { *m = MsgSoldierNotify{} }
func (m *MsgSoldierNotify) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierNotify) ProtoMessage()    {}

func (m *MsgSoldierNotify) GetSoldier() *Soldier {
	if m != nil {
		return m.Soldier
	}
	return nil
}

func (m *MsgSoldierNotify) SetSoldier(value *Soldier) {
	if m != nil {
		m.Soldier = value
	}
}

// 升级
type MsgSoldierLvRet struct {
	SchemeId         *int32 `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	RetCode          *int32 `protobuf:"varint,2,req,name=retCode" json:"retCode,omitempty"`
	Level            *int32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierLvRet) Reset()         { *m = MsgSoldierLvRet{} }
func (m *MsgSoldierLvRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierLvRet) ProtoMessage()    {}

func (m *MsgSoldierLvRet) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgSoldierLvRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierLvRet) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MsgSoldierLvRet) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgSoldierLvRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func (m *MsgSoldierLvRet) SetLevel(value int32) {
	if m != nil {
		if m.Level != nil {
			*m.Level = value
			return
		}
		m.Level = proto.Int32(value)
	}
}

// 魔物技能强化请求
type MsgSoldierSkillLvReq struct {
	SoldierId        *int32 `protobuf:"varint,1,req,name=soldierId" json:"soldierId,omitempty"`
	SkillId          *int32 `protobuf:"varint,2,req,name=skillId" json:"skillId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierSkillLvReq) Reset()         { *m = MsgSoldierSkillLvReq{} }
func (m *MsgSoldierSkillLvReq) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierSkillLvReq) ProtoMessage()    {}

func (m *MsgSoldierSkillLvReq) GetSoldierId() int32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *MsgSoldierSkillLvReq) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgSoldierSkillLvReq) SetSoldierId(value int32) {
	if m != nil {
		if m.SoldierId != nil {
			*m.SoldierId = value
			return
		}
		m.SoldierId = proto.Int32(value)
	}
}

func (m *MsgSoldierSkillLvReq) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

type MsgSoldierSkillLvRet struct {
	RetCode          *int32 `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSoldierSkillLvRet) Reset()         { *m = MsgSoldierSkillLvRet{} }
func (m *MsgSoldierSkillLvRet) String() string { return proto.CompactTextString(m) }
func (*MsgSoldierSkillLvRet) ProtoMessage()    {}

func (m *MsgSoldierSkillLvRet) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgSoldierSkillLvRet) SetRetCode(value int32) {
	if m != nil {
		if m.RetCode != nil {
			*m.RetCode = value
			return
		}
		m.RetCode = proto.Int32(value)
	}
}

func init() {
}
