// Code generated by protoc-gen-go.
// source: award.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type AwardInfo struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Code             *int32 `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Amount           *int32 `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AwardInfo) Reset()         { *m = AwardInfo{} }
func (m *AwardInfo) String() string { return proto.CompactTextString(m) }
func (*AwardInfo) ProtoMessage()    {}

func (m *AwardInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AwardInfo) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AwardInfo) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *AwardInfo) SetType(value int32) {
	if m != nil {
		if m.Type != nil {
			*m.Type = value
			return
		}
		m.Type = proto.Int32(value)
	}
}

func (m *AwardInfo) SetCode(value int32) {
	if m != nil {
		if m.Code != nil {
			*m.Code = value
			return
		}
		m.Code = proto.Int32(value)
	}
}

func (m *AwardInfo) SetAmount(value int32) {
	if m != nil {
		if m.Amount != nil {
			*m.Amount = value
			return
		}
		m.Amount = proto.Int32(value)
	}
}

func init() {
}
