// Code generated by protoc-gen-go.
// source: account_cache.proto
// DO NOT EDIT!

/*
Package cache is a generated protocol buffer package.

It is generated from these files:
	account_cache.proto

It has these top-level messages:
	AccountCache
*/
package cache

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type AccountCache struct {
	RoleId      int64  `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Source      string `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	SourceToken string `protobuf:"bytes,4,opt,name=sourceToken" json:"sourceToken,omitempty"`
	LoginTime   int64  `protobuf:"varint,5,opt,name=loginTime" json:"loginTime,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *AccountCache) Reset()         { *m = AccountCache{} }
func (m *AccountCache) String() string { return proto.CompactTextString(m) }
func (*AccountCache) ProtoMessage()    {}

func init() {
}
