// Code generated by protoc-gen-go.
// source: achievement_cache.proto
// DO NOT EDIT!

/*
	Package cache is a generated protocol buffer package.

	It is generated from these files:
		achievement_cache.proto
		building_cache.proto
		decoration.proto
		fb_cache.proto
		fight_report_cache.proto
		friend_cache.proto
		gm_cache.proto
		hero_cache.proto
		item_cache.proto
		king_cache.proto
		mall_cache.proto
		map_cache.proto
		mission_cache.proto
		pvp_cache.proto
		role_cache.proto
		sign_cache.proto
		soldier_cache.proto
		stage_cache.proto

	It has these top-level messages:
		AchievementCache
*/
package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type AchievementCache struct {
	SchemeId         *int32          `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	ReachedNum       *int32          `protobuf:"varint,2,req,name=reachedNum" json:"reachedNum,omitempty"`
	FinishLevel      *int32          `protobuf:"varint,3,req,name=finishLevel" json:"finishLevel,omitempty"`
	TargetNum        map[int32]int32 `protobuf:"bytes,4,rep,name=targetNum" json:"targetNum,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AwardId          map[int32]int32 `protobuf:"bytes,5,rep,name=awardId" json:"awardId,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *AchievementCache) Reset()         { *m = AchievementCache{} }
func (m *AchievementCache) String() string { return proto.CompactTextString(m) }
func (*AchievementCache) ProtoMessage()    {}

func (m *AchievementCache) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *AchievementCache) GetReachedNum() int32 {
	if m != nil && m.ReachedNum != nil {
		return *m.ReachedNum
	}
	return 0
}

func (m *AchievementCache) GetFinishLevel() int32 {
	if m != nil && m.FinishLevel != nil {
		return *m.FinishLevel
	}
	return 0
}

func (m *AchievementCache) GetTargetNum() map[int32]int32 {
	if m != nil {
		return m.TargetNum
	}
	return nil
}

func (m *AchievementCache) GetAwardId() map[int32]int32 {
	if m != nil {
		return m.AwardId
	}
	return nil
}

func (m *AchievementCache) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *AchievementCache) SetReachedNum(value int32) {
	if m != nil {
		if m.ReachedNum != nil {
			*m.ReachedNum = value
			return
		}
		m.ReachedNum = proto.Int32(value)
	}
}

func (m *AchievementCache) SetFinishLevel(value int32) {
	if m != nil {
		if m.FinishLevel != nil {
			*m.FinishLevel = value
			return
		}
		m.FinishLevel = proto.Int32(value)
	}
}

func (m *AchievementCache) SetTargetNum(value map[int32]int32) {
	if m != nil {
		m.TargetNum = value
	}
}

func (m *AchievementCache) SetAwardId(value map[int32]int32) {
	if m != nil {
		m.AwardId = value
	}
}

func init() {
}
