// Code generated by protoc-gen-go.
// source: define.proto
// DO NOT EDIT!

/*
	Package define is a generated protocol buffer package.

	It is generated from these files:
		define.proto

	It has these top-level messages:
		MsgHelloReq
		MsgHelloRet
*/
package define

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MsgHelloReq struct {
	ServerId         *int32  `protobuf:"varint,1,req,name=serverId" json:"serverId,omitempty"`
	ServerType       *string `protobuf:"bytes,2,req,name=serverType" json:"serverType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgHelloReq) Reset()         { *m = MsgHelloReq{} }
func (m *MsgHelloReq) String() string { return proto.CompactTextString(m) }
func (*MsgHelloReq) ProtoMessage()    {}

func (m *MsgHelloReq) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *MsgHelloReq) GetServerType() string {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return ""
}

func (m *MsgHelloReq) SetServerId(value int32) {
	if m != nil {
		if m.ServerId != nil {
			*m.ServerId = value
			return
		}
		m.ServerId = proto.Int32(value)
	}
}

func (m *MsgHelloReq) SetServerType(value string) {
	if m != nil {
		if m.ServerType != nil {
			*m.ServerType = value
			return
		}
		m.ServerType = proto.String(value)
	}
}

type MsgHelloRet struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgHelloRet) Reset()         { *m = MsgHelloRet{} }
func (m *MsgHelloRet) String() string { return proto.CompactTextString(m) }
func (*MsgHelloRet) ProtoMessage()    {}

func (m *MsgHelloRet) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MsgHelloRet) SetErrorCode(value int32) {
	if m != nil {
		if m.ErrorCode != nil {
			*m.ErrorCode = value
			return
		}
		m.ErrorCode = proto.Int32(value)
	}
}

func init() {
}
