// Code generated by protoc-gen-go.
// source: static.proto
// DO NOT EDIT!

/*
	Package static is a generated protocol buffer package.

	It is generated from these files:
		static.proto

	It has these top-level messages:
		MsgStaticRoleCreate
		MsgStaticRoleLogin
		MsgStaticRoleChange
		MsgStaticKingSkill
		MsgStaticHero
		MsgStaticHeroDel
		MsgStaticSoldier
		MsgStaticBuilding
		MsgStaticStageLog
		MsgStaticResCollectLog
		MsgStaticStoneExchangeLog
		MsgStaticPayLog
		MsgStaticChargeLog
*/
package static

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type StageStatus int32

const (
	StageStatus_begin StageStatus = 0
	StageStatus_end   StageStatus = 1
)

var StageStatus_name = map[int32]string{
	0: "begin",
	1: "end",
}
var StageStatus_value = map[string]int32{
	"begin": 0,
	"end":   1,
}

func (x StageStatus) Enum() *StageStatus {
	p := new(StageStatus)
	*p = x
	return p
}
func (x StageStatus) String() string {
	return proto.EnumName(StageStatus_name, int32(x))
}
func (x *StageStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StageStatus_value, data, "StageStatus")
	if err != nil {
		return err
	}
	*x = StageStatus(value)
	return nil
}

type ResCollectType int32

const (
	ResCollectType_blood ResCollectType = 0
	ResCollectType_soul  ResCollectType = 1
)

var ResCollectType_name = map[int32]string{
	0: "blood",
	1: "soul",
}
var ResCollectType_value = map[string]int32{
	"blood": 0,
	"soul":  1,
}

func (x ResCollectType) Enum() *ResCollectType {
	p := new(ResCollectType)
	*p = x
	return p
}
func (x ResCollectType) String() string {
	return proto.EnumName(ResCollectType_name, int32(x))
}
func (x *ResCollectType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResCollectType_value, data, "ResCollectType")
	if err != nil {
		return err
	}
	*x = ResCollectType(value)
	return nil
}

type PayType int32

const (
	PayType_item               PayType = 0
	PayType_bloodUpKing        PayType = 1
	PayType_bloodExchagePvp    PayType = 2
	PayType_bloodBuyMappoint   PayType = 3
	PayType_bloodBuyDecoration PayType = 4
	PayType_soulUpKing         PayType = 5
	PayType_soulBuyMappoint    PayType = 6
	PayType_soulBuyDecoration  PayType = 7
	PayType_evolutionSpeedup   PayType = 8
	PayType_evolutionOnekey    PayType = 9
	PayType_upBuildingSpeedup  PayType = 10
	PayType_upBuildingOnekey   PayType = 11
	PayType_upKingskillSpeedup PayType = 12
	PayType_upKingskillOnekey  PayType = 13
)

var PayType_name = map[int32]string{
	0:  "item",
	1:  "bloodUpKing",
	2:  "bloodExchagePvp",
	3:  "bloodBuyMappoint",
	4:  "bloodBuyDecoration",
	5:  "soulUpKing",
	6:  "soulBuyMappoint",
	7:  "soulBuyDecoration",
	8:  "evolutionSpeedup",
	9:  "evolutionOnekey",
	10: "upBuildingSpeedup",
	11: "upBuildingOnekey",
	12: "upKingskillSpeedup",
	13: "upKingskillOnekey",
}
var PayType_value = map[string]int32{
	"item":               0,
	"bloodUpKing":        1,
	"bloodExchagePvp":    2,
	"bloodBuyMappoint":   3,
	"bloodBuyDecoration": 4,
	"soulUpKing":         5,
	"soulBuyMappoint":    6,
	"soulBuyDecoration":  7,
	"evolutionSpeedup":   8,
	"evolutionOnekey":    9,
	"upBuildingSpeedup":  10,
	"upBuildingOnekey":   11,
	"upKingskillSpeedup": 12,
	"upKingskillOnekey":  13,
}

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}
func (x PayType) String() string {
	return proto.EnumName(PayType_name, int32(x))
}
func (x *PayType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PayType_value, data, "PayType")
	if err != nil {
		return err
	}
	*x = PayType(value)
	return nil
}

type MsgStaticCode int32

const (
	MsgStaticCode_RoleCreate       MsgStaticCode = 1000001
	MsgStaticCode_RoleLogin        MsgStaticCode = 1000002
	MsgStaticCode_RoleChange       MsgStaticCode = 1000003
	MsgStaticCode_KingSkill        MsgStaticCode = 1000004
	MsgStaticCode_Hero             MsgStaticCode = 1000005
	MsgStaticCode_HeroDel          MsgStaticCode = 1000006
	MsgStaticCode_Soldier          MsgStaticCode = 1000007
	MsgStaticCode_Building         MsgStaticCode = 1000008
	MsgStaticCode_StageLog         MsgStaticCode = 1000009
	MsgStaticCode_ResCollectLog    MsgStaticCode = 1000010
	MsgStaticCode_StoneExchangeLog MsgStaticCode = 1000011
	MsgStaticCode_PayLog           MsgStaticCode = 1000012
	MsgStaticCode_ChargeLog        MsgStaticCode = 1000013
)

var MsgStaticCode_name = map[int32]string{
	1000001: "RoleCreate",
	1000002: "RoleLogin",
	1000003: "RoleChange",
	1000004: "KingSkill",
	1000005: "Hero",
	1000006: "HeroDel",
	1000007: "Soldier",
	1000008: "Building",
	1000009: "StageLog",
	1000010: "ResCollectLog",
	1000011: "StoneExchangeLog",
	1000012: "PayLog",
	1000013: "ChargeLog",
}
var MsgStaticCode_value = map[string]int32{
	"RoleCreate":       1000001,
	"RoleLogin":        1000002,
	"RoleChange":       1000003,
	"KingSkill":        1000004,
	"Hero":             1000005,
	"HeroDel":          1000006,
	"Soldier":          1000007,
	"Building":         1000008,
	"StageLog":         1000009,
	"ResCollectLog":    1000010,
	"StoneExchangeLog": 1000011,
	"PayLog":           1000012,
	"ChargeLog":        1000013,
}

func (x MsgStaticCode) Enum() *MsgStaticCode {
	p := new(MsgStaticCode)
	*p = x
	return p
}
func (x MsgStaticCode) String() string {
	return proto.EnumName(MsgStaticCode_name, int32(x))
}
func (x *MsgStaticCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgStaticCode_value, data, "MsgStaticCode")
	if err != nil {
		return err
	}
	*x = MsgStaticCode(value)
	return nil
}

type MsgStaticRoleCreate struct {
	RoleUid          *int64  `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Lv               *int32  `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Stone            *int32  `protobuf:"varint,3,req,name=stone" json:"stone,omitempty"`
	Gold             *int32  `protobuf:"varint,4,req,name=gold" json:"gold,omitempty"`
	FreeGold         *int32  `protobuf:"varint,5,req,name=free_gold" json:"free_gold,omitempty"`
	Trophy           *int32  `protobuf:"varint,6,req,name=trophy" json:"trophy,omitempty"`
	TotalCharge      *int32  `protobuf:"varint,7,req,name=total_charge" json:"total_charge,omitempty"`
	LastLoginTime    *int64  `protobuf:"varint,8,req,name=last_login_time" json:"last_login_time,omitempty"`
	Ip               *string `protobuf:"bytes,9,req,name=ip" json:"ip,omitempty"`
	CreateTime       *int64  `protobuf:"varint,10,req,name=create_time" json:"create_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgStaticRoleCreate) Reset()         { *m = MsgStaticRoleCreate{} }
func (m *MsgStaticRoleCreate) String() string { return proto.CompactTextString(m) }
func (*MsgStaticRoleCreate) ProtoMessage()    {}

func (m *MsgStaticRoleCreate) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetStone() int32 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetFreeGold() int32 {
	if m != nil && m.FreeGold != nil {
		return *m.FreeGold
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetTrophy() int32 {
	if m != nil && m.Trophy != nil {
		return *m.Trophy
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetTotalCharge() int32 {
	if m != nil && m.TotalCharge != nil {
		return *m.TotalCharge
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetLastLoginTime() int64 {
	if m != nil && m.LastLoginTime != nil {
		return *m.LastLoginTime
	}
	return 0
}

func (m *MsgStaticRoleCreate) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *MsgStaticRoleCreate) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *MsgStaticRoleCreate) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticRoleCreate) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetStone(value int32) {
	if m != nil {
		if m.Stone != nil {
			*m.Stone = value
			return
		}
		m.Stone = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetGold(value int32) {
	if m != nil {
		if m.Gold != nil {
			*m.Gold = value
			return
		}
		m.Gold = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetFreeGold(value int32) {
	if m != nil {
		if m.FreeGold != nil {
			*m.FreeGold = value
			return
		}
		m.FreeGold = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetTrophy(value int32) {
	if m != nil {
		if m.Trophy != nil {
			*m.Trophy = value
			return
		}
		m.Trophy = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetTotalCharge(value int32) {
	if m != nil {
		if m.TotalCharge != nil {
			*m.TotalCharge = value
			return
		}
		m.TotalCharge = proto.Int32(value)
	}
}

func (m *MsgStaticRoleCreate) SetLastLoginTime(value int64) {
	if m != nil {
		if m.LastLoginTime != nil {
			*m.LastLoginTime = value
			return
		}
		m.LastLoginTime = proto.Int64(value)
	}
}

func (m *MsgStaticRoleCreate) SetIp(value string) {
	if m != nil {
		if m.Ip != nil {
			*m.Ip = value
			return
		}
		m.Ip = proto.String(value)
	}
}

func (m *MsgStaticRoleCreate) SetCreateTime(value int64) {
	if m != nil {
		if m.CreateTime != nil {
			*m.CreateTime = value
			return
		}
		m.CreateTime = proto.Int64(value)
	}
}

type MsgStaticRoleLogin struct {
	RoleUid          *int64  `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Lv               *int32  `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Stone            *int32  `protobuf:"varint,3,req,name=stone" json:"stone,omitempty"`
	Gold             *int32  `protobuf:"varint,4,req,name=gold" json:"gold,omitempty"`
	FreeGold         *int32  `protobuf:"varint,5,req,name=free_gold" json:"free_gold,omitempty"`
	Trophy           *int32  `protobuf:"varint,6,req,name=trophy" json:"trophy,omitempty"`
	TotalCharge      *int32  `protobuf:"varint,7,req,name=total_charge" json:"total_charge,omitempty"`
	LastLoginTime    *int64  `protobuf:"varint,8,req,name=last_login_time" json:"last_login_time,omitempty"`
	Ip               *string `protobuf:"bytes,9,req,name=ip" json:"ip,omitempty"`
	CreateTime       *int64  `protobuf:"varint,10,req,name=create_time" json:"create_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgStaticRoleLogin) Reset()         { *m = MsgStaticRoleLogin{} }
func (m *MsgStaticRoleLogin) String() string { return proto.CompactTextString(m) }
func (*MsgStaticRoleLogin) ProtoMessage()    {}

func (m *MsgStaticRoleLogin) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetStone() int32 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetFreeGold() int32 {
	if m != nil && m.FreeGold != nil {
		return *m.FreeGold
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetTrophy() int32 {
	if m != nil && m.Trophy != nil {
		return *m.Trophy
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetTotalCharge() int32 {
	if m != nil && m.TotalCharge != nil {
		return *m.TotalCharge
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetLastLoginTime() int64 {
	if m != nil && m.LastLoginTime != nil {
		return *m.LastLoginTime
	}
	return 0
}

func (m *MsgStaticRoleLogin) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *MsgStaticRoleLogin) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *MsgStaticRoleLogin) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticRoleLogin) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetStone(value int32) {
	if m != nil {
		if m.Stone != nil {
			*m.Stone = value
			return
		}
		m.Stone = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetGold(value int32) {
	if m != nil {
		if m.Gold != nil {
			*m.Gold = value
			return
		}
		m.Gold = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetFreeGold(value int32) {
	if m != nil {
		if m.FreeGold != nil {
			*m.FreeGold = value
			return
		}
		m.FreeGold = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetTrophy(value int32) {
	if m != nil {
		if m.Trophy != nil {
			*m.Trophy = value
			return
		}
		m.Trophy = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetTotalCharge(value int32) {
	if m != nil {
		if m.TotalCharge != nil {
			*m.TotalCharge = value
			return
		}
		m.TotalCharge = proto.Int32(value)
	}
}

func (m *MsgStaticRoleLogin) SetLastLoginTime(value int64) {
	if m != nil {
		if m.LastLoginTime != nil {
			*m.LastLoginTime = value
			return
		}
		m.LastLoginTime = proto.Int64(value)
	}
}

func (m *MsgStaticRoleLogin) SetIp(value string) {
	if m != nil {
		if m.Ip != nil {
			*m.Ip = value
			return
		}
		m.Ip = proto.String(value)
	}
}

func (m *MsgStaticRoleLogin) SetCreateTime(value int64) {
	if m != nil {
		if m.CreateTime != nil {
			*m.CreateTime = value
			return
		}
		m.CreateTime = proto.Int64(value)
	}
}

type MsgStaticRoleChange struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Type             *int32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Value            *int32 `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticRoleChange) Reset()         { *m = MsgStaticRoleChange{} }
func (m *MsgStaticRoleChange) String() string { return proto.CompactTextString(m) }
func (*MsgStaticRoleChange) ProtoMessage()    {}

func (m *MsgStaticRoleChange) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticRoleChange) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgStaticRoleChange) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *MsgStaticRoleChange) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticRoleChange) SetType(value int32) {
	if m != nil {
		if m.Type != nil {
			*m.Type = value
			return
		}
		m.Type = proto.Int32(value)
	}
}

func (m *MsgStaticRoleChange) SetValue(value int32) {
	if m != nil {
		if m.Value != nil {
			*m.Value = value
			return
		}
		m.Value = proto.Int32(value)
	}
}

type MsgStaticKingSkill struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	SkillId          *int32 `protobuf:"varint,2,req,name=skill_id" json:"skill_id,omitempty"`
	SkillLv          *int32 `protobuf:"varint,3,req,name=skill_lv" json:"skill_lv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticKingSkill) Reset()         { *m = MsgStaticKingSkill{} }
func (m *MsgStaticKingSkill) String() string { return proto.CompactTextString(m) }
func (*MsgStaticKingSkill) ProtoMessage()    {}

func (m *MsgStaticKingSkill) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticKingSkill) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *MsgStaticKingSkill) GetSkillLv() int32 {
	if m != nil && m.SkillLv != nil {
		return *m.SkillLv
	}
	return 0
}

func (m *MsgStaticKingSkill) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticKingSkill) SetSkillId(value int32) {
	if m != nil {
		if m.SkillId != nil {
			*m.SkillId = value
			return
		}
		m.SkillId = proto.Int32(value)
	}
}

func (m *MsgStaticKingSkill) SetSkillLv(value int32) {
	if m != nil {
		if m.SkillLv != nil {
			*m.SkillLv = value
			return
		}
		m.SkillLv = proto.Int32(value)
	}
}

type MsgStaticHero struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Uid              *int64 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	SchemeId         *int32 `protobuf:"varint,3,req,name=scheme_id" json:"scheme_id,omitempty"`
	Lv               *int32 `protobuf:"varint,4,req,name=lv" json:"lv,omitempty"`
	Stage            *int32 `protobuf:"varint,5,req,name=stage" json:"stage,omitempty"`
	Rank             *int32 `protobuf:"varint,6,req,name=rank" json:"rank,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticHero) Reset()         { *m = MsgStaticHero{} }
func (m *MsgStaticHero) String() string { return proto.CompactTextString(m) }
func (*MsgStaticHero) ProtoMessage()    {}

func (m *MsgStaticHero) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticHero) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgStaticHero) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticHero) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticHero) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *MsgStaticHero) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *MsgStaticHero) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticHero) SetUid(value int64) {
	if m != nil {
		if m.Uid != nil {
			*m.Uid = value
			return
		}
		m.Uid = proto.Int64(value)
	}
}

func (m *MsgStaticHero) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticHero) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticHero) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

func (m *MsgStaticHero) SetRank(value int32) {
	if m != nil {
		if m.Rank != nil {
			*m.Rank = value
			return
		}
		m.Rank = proto.Int32(value)
	}
}

type MsgStaticHeroDel struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Uid              *int64 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticHeroDel) Reset()         { *m = MsgStaticHeroDel{} }
func (m *MsgStaticHeroDel) String() string { return proto.CompactTextString(m) }
func (*MsgStaticHeroDel) ProtoMessage()    {}

func (m *MsgStaticHeroDel) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticHeroDel) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgStaticHeroDel) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticHeroDel) SetUid(value int64) {
	if m != nil {
		if m.Uid != nil {
			*m.Uid = value
			return
		}
		m.Uid = proto.Int64(value)
	}
}

type MsgStaticSoldier struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	SchemeId         *int32 `protobuf:"varint,2,req,name=scheme_id" json:"scheme_id,omitempty"`
	Num              *int32 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	Lv               *int32 `protobuf:"varint,4,req,name=lv" json:"lv,omitempty"`
	Stage            *int32 `protobuf:"varint,5,req,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticSoldier) Reset()         { *m = MsgStaticSoldier{} }
func (m *MsgStaticSoldier) String() string { return proto.CompactTextString(m) }
func (*MsgStaticSoldier) ProtoMessage()    {}

func (m *MsgStaticSoldier) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticSoldier) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticSoldier) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *MsgStaticSoldier) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticSoldier) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func (m *MsgStaticSoldier) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticSoldier) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticSoldier) SetNum(value int32) {
	if m != nil {
		if m.Num != nil {
			*m.Num = value
			return
		}
		m.Num = proto.Int32(value)
	}
}

func (m *MsgStaticSoldier) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticSoldier) SetStage(value int32) {
	if m != nil {
		if m.Stage != nil {
			*m.Stage = value
			return
		}
		m.Stage = proto.Int32(value)
	}
}

type MsgStaticBuilding struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Uid              *int64 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	SchemeId         *int32 `protobuf:"varint,3,req,name=scheme_id" json:"scheme_id,omitempty"`
	Lv               *int32 `protobuf:"varint,4,req,name=lv" json:"lv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticBuilding) Reset()         { *m = MsgStaticBuilding{} }
func (m *MsgStaticBuilding) String() string { return proto.CompactTextString(m) }
func (*MsgStaticBuilding) ProtoMessage()    {}

func (m *MsgStaticBuilding) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticBuilding) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgStaticBuilding) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticBuilding) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticBuilding) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticBuilding) SetUid(value int64) {
	if m != nil {
		if m.Uid != nil {
			*m.Uid = value
			return
		}
		m.Uid = proto.Int64(value)
	}
}

func (m *MsgStaticBuilding) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticBuilding) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

type MsgStaticStageLog struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Lv               *int32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	SchemeId         *int32 `protobuf:"varint,3,req,name=scheme_id" json:"scheme_id,omitempty"`
	Status           *int32 `protobuf:"varint,4,req,name=status" json:"status,omitempty"`
	IsPassed         *int32 `protobuf:"varint,5,req,name=is_passed" json:"is_passed,omitempty"`
	TimeStamp        *int64 `protobuf:"varint,6,req,name=time_stamp" json:"time_stamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticStageLog) Reset()         { *m = MsgStaticStageLog{} }
func (m *MsgStaticStageLog) String() string { return proto.CompactTextString(m) }
func (*MsgStaticStageLog) ProtoMessage()    {}

func (m *MsgStaticStageLog) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticStageLog) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticStageLog) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticStageLog) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *MsgStaticStageLog) GetIsPassed() int32 {
	if m != nil && m.IsPassed != nil {
		return *m.IsPassed
	}
	return 0
}

func (m *MsgStaticStageLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MsgStaticStageLog) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticStageLog) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticStageLog) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticStageLog) SetStatus(value int32) {
	if m != nil {
		if m.Status != nil {
			*m.Status = value
			return
		}
		m.Status = proto.Int32(value)
	}
}

func (m *MsgStaticStageLog) SetIsPassed(value int32) {
	if m != nil {
		if m.IsPassed != nil {
			*m.IsPassed = value
			return
		}
		m.IsPassed = proto.Int32(value)
	}
}

func (m *MsgStaticStageLog) SetTimeStamp(value int64) {
	if m != nil {
		if m.TimeStamp != nil {
			*m.TimeStamp = value
			return
		}
		m.TimeStamp = proto.Int64(value)
	}
}

type MsgStaticResCollectLog struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Type             *int32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Value            *int32 `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	TimeStamp        *int64 `protobuf:"varint,4,req,name=time_stamp" json:"time_stamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticResCollectLog) Reset()         { *m = MsgStaticResCollectLog{} }
func (m *MsgStaticResCollectLog) String() string { return proto.CompactTextString(m) }
func (*MsgStaticResCollectLog) ProtoMessage()    {}

func (m *MsgStaticResCollectLog) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticResCollectLog) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgStaticResCollectLog) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *MsgStaticResCollectLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MsgStaticResCollectLog) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticResCollectLog) SetType(value int32) {
	if m != nil {
		if m.Type != nil {
			*m.Type = value
			return
		}
		m.Type = proto.Int32(value)
	}
}

func (m *MsgStaticResCollectLog) SetValue(value int32) {
	if m != nil {
		if m.Value != nil {
			*m.Value = value
			return
		}
		m.Value = proto.Int32(value)
	}
}

func (m *MsgStaticResCollectLog) SetTimeStamp(value int64) {
	if m != nil {
		if m.TimeStamp != nil {
			*m.TimeStamp = value
			return
		}
		m.TimeStamp = proto.Int64(value)
	}
}

type MsgStaticStoneExchangeLog struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	SchemeId         *int32 `protobuf:"varint,2,req,name=scheme_id" json:"scheme_id,omitempty"`
	TimeStamp        *int64 `protobuf:"varint,3,req,name=time_stamp" json:"time_stamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticStoneExchangeLog) Reset()         { *m = MsgStaticStoneExchangeLog{} }
func (m *MsgStaticStoneExchangeLog) String() string { return proto.CompactTextString(m) }
func (*MsgStaticStoneExchangeLog) ProtoMessage()    {}

func (m *MsgStaticStoneExchangeLog) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticStoneExchangeLog) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticStoneExchangeLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MsgStaticStoneExchangeLog) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticStoneExchangeLog) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticStoneExchangeLog) SetTimeStamp(value int64) {
	if m != nil {
		if m.TimeStamp != nil {
			*m.TimeStamp = value
			return
		}
		m.TimeStamp = proto.Int64(value)
	}
}

type MsgStaticPayLog struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Lv               *int32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	Type             *int32 `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	SchemeId         *int32 `protobuf:"varint,4,req,name=scheme_id" json:"scheme_id,omitempty"`
	Gold             *int32 `protobuf:"varint,5,req,name=gold" json:"gold,omitempty"`
	TimeStamp        *int64 `protobuf:"varint,6,req,name=time_stamp" json:"time_stamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticPayLog) Reset()         { *m = MsgStaticPayLog{} }
func (m *MsgStaticPayLog) String() string { return proto.CompactTextString(m) }
func (*MsgStaticPayLog) ProtoMessage()    {}

func (m *MsgStaticPayLog) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticPayLog) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticPayLog) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgStaticPayLog) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticPayLog) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *MsgStaticPayLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MsgStaticPayLog) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticPayLog) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticPayLog) SetType(value int32) {
	if m != nil {
		if m.Type != nil {
			*m.Type = value
			return
		}
		m.Type = proto.Int32(value)
	}
}

func (m *MsgStaticPayLog) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticPayLog) SetGold(value int32) {
	if m != nil {
		if m.Gold != nil {
			*m.Gold = value
			return
		}
		m.Gold = proto.Int32(value)
	}
}

func (m *MsgStaticPayLog) SetTimeStamp(value int64) {
	if m != nil {
		if m.TimeStamp != nil {
			*m.TimeStamp = value
			return
		}
		m.TimeStamp = proto.Int64(value)
	}
}

type MsgStaticChargeLog struct {
	RoleUid          *int64 `protobuf:"varint,1,req,name=role_uid" json:"role_uid,omitempty"`
	Lv               *int32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	SchemeId         *int32 `protobuf:"varint,3,req,name=scheme_id" json:"scheme_id,omitempty"`
	Gold             *int32 `protobuf:"varint,4,req,name=gold" json:"gold,omitempty"`
	Price            *int32 `protobuf:"varint,5,req,name=price" json:"price,omitempty"`
	TimeStamp        *int64 `protobuf:"varint,6,req,name=time_stamp" json:"time_stamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgStaticChargeLog) Reset()         { *m = MsgStaticChargeLog{} }
func (m *MsgStaticChargeLog) String() string { return proto.CompactTextString(m) }
func (*MsgStaticChargeLog) ProtoMessage()    {}

func (m *MsgStaticChargeLog) GetRoleUid() int64 {
	if m != nil && m.RoleUid != nil {
		return *m.RoleUid
	}
	return 0
}

func (m *MsgStaticChargeLog) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *MsgStaticChargeLog) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *MsgStaticChargeLog) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *MsgStaticChargeLog) GetPrice() int32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *MsgStaticChargeLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MsgStaticChargeLog) SetRoleUid(value int64) {
	if m != nil {
		if m.RoleUid != nil {
			*m.RoleUid = value
			return
		}
		m.RoleUid = proto.Int64(value)
	}
}

func (m *MsgStaticChargeLog) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *MsgStaticChargeLog) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *MsgStaticChargeLog) SetGold(value int32) {
	if m != nil {
		if m.Gold != nil {
			*m.Gold = value
			return
		}
		m.Gold = proto.Int32(value)
	}
}

func (m *MsgStaticChargeLog) SetPrice(value int32) {
	if m != nil {
		if m.Price != nil {
			*m.Price = value
			return
		}
		m.Price = proto.Int32(value)
	}
}

func (m *MsgStaticChargeLog) SetTimeStamp(value int64) {
	if m != nil {
		if m.TimeStamp != nil {
			*m.TimeStamp = value
			return
		}
		m.TimeStamp = proto.Int64(value)
	}
}

func init() {
	proto.RegisterEnum("static.StageStatus", StageStatus_name, StageStatus_value)
	proto.RegisterEnum("static.ResCollectType", ResCollectType_name, ResCollectType_value)
	proto.RegisterEnum("static.PayType", PayType_name, PayType_value)
	proto.RegisterEnum("static.MsgStaticCode", MsgStaticCode_name, MsgStaticCode_value)
}
