// Code generated by protoc-gen-go.
// source: activity_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ActivityRoleCache struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Index            *int32 `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	Status           *int32 `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	Condition        *int64 `protobuf:"varint,4,req,name=condition" json:"condition,omitempty"`
	Timestamp        *int64 `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	Version          *int64 `protobuf:"varint,6,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivityRoleCache) Reset()         { *m = ActivityRoleCache{} }
func (m *ActivityRoleCache) String() string { return proto.CompactTextString(m) }
func (*ActivityRoleCache) ProtoMessage()    {}

func (m *ActivityRoleCache) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ActivityRoleCache) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ActivityRoleCache) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ActivityRoleCache) GetCondition() int64 {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return 0
}

func (m *ActivityRoleCache) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ActivityRoleCache) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ActivityRoleCache) SetId(value int32) {
	if m != nil {
		if m.Id != nil {
			*m.Id = value
			return
		}
		m.Id = proto.Int32(value)
	}
}

func (m *ActivityRoleCache) SetIndex(value int32) {
	if m != nil {
		if m.Index != nil {
			*m.Index = value
			return
		}
		m.Index = proto.Int32(value)
	}
}

func (m *ActivityRoleCache) SetStatus(value int32) {
	if m != nil {
		if m.Status != nil {
			*m.Status = value
			return
		}
		m.Status = proto.Int32(value)
	}
}

func (m *ActivityRoleCache) SetCondition(value int64) {
	if m != nil {
		if m.Condition != nil {
			*m.Condition = value
			return
		}
		m.Condition = proto.Int64(value)
	}
}

func (m *ActivityRoleCache) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *ActivityRoleCache) SetVersion(value int64) {
	if m != nil {
		if m.Version != nil {
			*m.Version = value
			return
		}
		m.Version = proto.Int64(value)
	}
}

func init() {
}
