// Code generated by protoc-gen-go.
// source: pvp_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type PvpCache struct {
	FightHeroList    []int64 `protobuf:"varint,1,rep,name=fight_hero_list" json:"fight_hero_list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PvpCache) Reset()         { *m = PvpCache{} }
func (m *PvpCache) String() string { return proto.CompactTextString(m) }
func (*PvpCache) ProtoMessage()    {}

func (m *PvpCache) GetFightHeroList() []int64 {
	if m != nil {
		return m.FightHeroList
	}
	return nil
}

func (m *PvpCache) SetFightHeroList(value []int64) {
	if m != nil {
		m.FightHeroList = value
	}
}

func init() {
}
