// Code generated by protoc-gen-go.
// source: fb_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FbCache struct {
	SchemeId         *int32          `protobuf:"varint,1,req,name=schemeId" json:"schemeId,omitempty"`
	Timestamp        *int64          `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	AttackedTimes    map[int32]int32 `protobuf:"bytes,3,rep,name=attackedTimes" json:"attackedTimes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FbCache) Reset()         { *m = FbCache{} }
func (m *FbCache) String() string { return proto.CompactTextString(m) }
func (*FbCache) ProtoMessage()    {}

func (m *FbCache) GetSchemeId() int32 {
	if m != nil && m.SchemeId != nil {
		return *m.SchemeId
	}
	return 0
}

func (m *FbCache) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *FbCache) GetAttackedTimes() map[int32]int32 {
	if m != nil {
		return m.AttackedTimes
	}
	return nil
}

func (m *FbCache) SetSchemeId(value int32) {
	if m != nil {
		if m.SchemeId != nil {
			*m.SchemeId = value
			return
		}
		m.SchemeId = proto.Int32(value)
	}
}

func (m *FbCache) SetTimestamp(value int64) {
	if m != nil {
		if m.Timestamp != nil {
			*m.Timestamp = value
			return
		}
		m.Timestamp = proto.Int64(value)
	}
}

func (m *FbCache) SetAttackedTimes(value map[int32]int32) {
	if m != nil {
		m.AttackedTimes = value
	}
}

func init() {
}
