// Code generated by protoc-gen-go.
// source: role_cache.proto
// DO NOT EDIT!

package cache

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RoleCache struct {
	Uid                  *int64  `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Nickname             *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	NicknameFlag         *int32  `protobuf:"varint,3,req,name=nickname_flag" json:"nickname_flag,omitempty"`
	Lv                   *int32  `protobuf:"varint,4,req,name=lv" json:"lv,omitempty"`
	Exp                  *int32  `protobuf:"varint,5,req,name=exp" json:"exp,omitempty"`
	Order                *int32  `protobuf:"varint,6,req,name=order" json:"order,omitempty"`
	OrderBuynum          *int32  `protobuf:"varint,7,req,name=order_buynum" json:"order_buynum,omitempty"`
	OrderTimestamp       *int64  `protobuf:"varint,8,req,name=order_timestamp" json:"order_timestamp,omitempty"`
	Spirit               *int32  `protobuf:"varint,9,req,name=spirit" json:"spirit,omitempty"`
	SpiritBuynum         *int32  `protobuf:"varint,10,req,name=spirit_buynum" json:"spirit_buynum,omitempty"`
	SpiritTimestamp      *int64  `protobuf:"varint,11,req,name=spirit_timestamp" json:"spirit_timestamp,omitempty"`
	Soul                 *int64  `protobuf:"varint,12,req,name=soul" json:"soul,omitempty"`
	Blood                *int64  `protobuf:"varint,13,req,name=blood" json:"blood,omitempty"`
	Stone                *int32  `protobuf:"varint,14,req,name=stone" json:"stone,omitempty"`
	Gold                 *int32  `protobuf:"varint,15,req,name=gold" json:"gold,omitempty"`
	FreeGold             *int32  `protobuf:"varint,16,req,name=free_gold" json:"free_gold,omitempty"`
	Trophy               *int32  `protobuf:"varint,17,req,name=trophy" json:"trophy,omitempty"`
	LeagueLv             *int32  `protobuf:"varint,18,req,name=leagueLv" json:"leagueLv,omitempty"`
	AttackWinCount       *int32  `protobuf:"varint,19,req,name=attack_win_count" json:"attack_win_count,omitempty"`
	DefenceWinCount      *int32  `protobuf:"varint,20,req,name=defence_win_count" json:"defence_win_count,omitempty"`
	Shield               *int64  `protobuf:"varint,21,req,name=shield" json:"shield,omitempty"`
	Vip                  *int64  `protobuf:"varint,22,req,name=vip" json:"vip,omitempty"`
	ChatFreeTime         *int32  `protobuf:"varint,23,req,name=chat_free_time" json:"chat_free_time,omitempty"`
	ChatRefreshTimestamp *int64  `protobuf:"varint,24,req,name=chat_refresh_timestamp" json:"chat_refresh_timestamp,omitempty"`
	MagicQueueType       *int32  `protobuf:"varint,25,req,name=magic_queue_type" json:"magic_queue_type,omitempty"`
	MagicQueueId         *int64  `protobuf:"varint,26,req,name=magic_queue_id" json:"magic_queue_id,omitempty"`
	NewPlayerGuideStep   *int32  `protobuf:"varint,27,req,name=new_player_guide_step" json:"new_player_guide_step,omitempty"`
	LoginTime            *int64  `protobuf:"varint,28,req,name=loginTime" json:"loginTime,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *RoleCache) Reset()         { *m = RoleCache{} }
func (m *RoleCache) String() string { return proto.CompactTextString(m) }
func (*RoleCache) ProtoMessage()    {}

func (m *RoleCache) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *RoleCache) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *RoleCache) GetNicknameFlag() int32 {
	if m != nil && m.NicknameFlag != nil {
		return *m.NicknameFlag
	}
	return 0
}

func (m *RoleCache) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *RoleCache) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *RoleCache) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

func (m *RoleCache) GetOrderBuynum() int32 {
	if m != nil && m.OrderBuynum != nil {
		return *m.OrderBuynum
	}
	return 0
}

func (m *RoleCache) GetOrderTimestamp() int64 {
	if m != nil && m.OrderTimestamp != nil {
		return *m.OrderTimestamp
	}
	return 0
}

func (m *RoleCache) GetSpirit() int32 {
	if m != nil && m.Spirit != nil {
		return *m.Spirit
	}
	return 0
}

func (m *RoleCache) GetSpiritBuynum() int32 {
	if m != nil && m.SpiritBuynum != nil {
		return *m.SpiritBuynum
	}
	return 0
}

func (m *RoleCache) GetSpiritTimestamp() int64 {
	if m != nil && m.SpiritTimestamp != nil {
		return *m.SpiritTimestamp
	}
	return 0
}

func (m *RoleCache) GetSoul() int64 {
	if m != nil && m.Soul != nil {
		return *m.Soul
	}
	return 0
}

func (m *RoleCache) GetBlood() int64 {
	if m != nil && m.Blood != nil {
		return *m.Blood
	}
	return 0
}

func (m *RoleCache) GetStone() int32 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func (m *RoleCache) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *RoleCache) GetFreeGold() int32 {
	if m != nil && m.FreeGold != nil {
		return *m.FreeGold
	}
	return 0
}

func (m *RoleCache) GetTrophy() int32 {
	if m != nil && m.Trophy != nil {
		return *m.Trophy
	}
	return 0
}

func (m *RoleCache) GetLeagueLv() int32 {
	if m != nil && m.LeagueLv != nil {
		return *m.LeagueLv
	}
	return 0
}

func (m *RoleCache) GetAttackWinCount() int32 {
	if m != nil && m.AttackWinCount != nil {
		return *m.AttackWinCount
	}
	return 0
}

func (m *RoleCache) GetDefenceWinCount() int32 {
	if m != nil && m.DefenceWinCount != nil {
		return *m.DefenceWinCount
	}
	return 0
}

func (m *RoleCache) GetShield() int64 {
	if m != nil && m.Shield != nil {
		return *m.Shield
	}
	return 0
}

func (m *RoleCache) GetVip() int64 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *RoleCache) GetChatFreeTime() int32 {
	if m != nil && m.ChatFreeTime != nil {
		return *m.ChatFreeTime
	}
	return 0
}

func (m *RoleCache) GetChatRefreshTimestamp() int64 {
	if m != nil && m.ChatRefreshTimestamp != nil {
		return *m.ChatRefreshTimestamp
	}
	return 0
}

func (m *RoleCache) GetMagicQueueType() int32 {
	if m != nil && m.MagicQueueType != nil {
		return *m.MagicQueueType
	}
	return 0
}

func (m *RoleCache) GetMagicQueueId() int64 {
	if m != nil && m.MagicQueueId != nil {
		return *m.MagicQueueId
	}
	return 0
}

func (m *RoleCache) GetNewPlayerGuideStep() int32 {
	if m != nil && m.NewPlayerGuideStep != nil {
		return *m.NewPlayerGuideStep
	}
	return 0
}

func (m *RoleCache) GetLoginTime() int64 {
	if m != nil && m.LoginTime != nil {
		return *m.LoginTime
	}
	return 0
}

func (m *RoleCache) SetUid(value int64) {
	if m != nil {
		if m.Uid != nil {
			*m.Uid = value
			return
		}
		m.Uid = proto.Int64(value)
	}
}

func (m *RoleCache) SetNickname(value string) {
	if m != nil {
		if m.Nickname != nil {
			*m.Nickname = value
			return
		}
		m.Nickname = proto.String(value)
	}
}

func (m *RoleCache) SetNicknameFlag(value int32) {
	if m != nil {
		if m.NicknameFlag != nil {
			*m.NicknameFlag = value
			return
		}
		m.NicknameFlag = proto.Int32(value)
	}
}

func (m *RoleCache) SetLv(value int32) {
	if m != nil {
		if m.Lv != nil {
			*m.Lv = value
			return
		}
		m.Lv = proto.Int32(value)
	}
}

func (m *RoleCache) SetExp(value int32) {
	if m != nil {
		if m.Exp != nil {
			*m.Exp = value
			return
		}
		m.Exp = proto.Int32(value)
	}
}

func (m *RoleCache) SetOrder(value int32) {
	if m != nil {
		if m.Order != nil {
			*m.Order = value
			return
		}
		m.Order = proto.Int32(value)
	}
}

func (m *RoleCache) SetOrderBuynum(value int32) {
	if m != nil {
		if m.OrderBuynum != nil {
			*m.OrderBuynum = value
			return
		}
		m.OrderBuynum = proto.Int32(value)
	}
}

func (m *RoleCache) SetOrderTimestamp(value int64) {
	if m != nil {
		if m.OrderTimestamp != nil {
			*m.OrderTimestamp = value
			return
		}
		m.OrderTimestamp = proto.Int64(value)
	}
}

func (m *RoleCache) SetSpirit(value int32) {
	if m != nil {
		if m.Spirit != nil {
			*m.Spirit = value
			return
		}
		m.Spirit = proto.Int32(value)
	}
}

func (m *RoleCache) SetSpiritBuynum(value int32) {
	if m != nil {
		if m.SpiritBuynum != nil {
			*m.SpiritBuynum = value
			return
		}
		m.SpiritBuynum = proto.Int32(value)
	}
}

func (m *RoleCache) SetSpiritTimestamp(value int64) {
	if m != nil {
		if m.SpiritTimestamp != nil {
			*m.SpiritTimestamp = value
			return
		}
		m.SpiritTimestamp = proto.Int64(value)
	}
}

func (m *RoleCache) SetSoul(value int64) {
	if m != nil {
		if m.Soul != nil {
			*m.Soul = value
			return
		}
		m.Soul = proto.Int64(value)
	}
}

func (m *RoleCache) SetBlood(value int64) {
	if m != nil {
		if m.Blood != nil {
			*m.Blood = value
			return
		}
		m.Blood = proto.Int64(value)
	}
}

func (m *RoleCache) SetStone(value int32) {
	if m != nil {
		if m.Stone != nil {
			*m.Stone = value
			return
		}
		m.Stone = proto.Int32(value)
	}
}

func (m *RoleCache) SetGold(value int32) {
	if m != nil {
		if m.Gold != nil {
			*m.Gold = value
			return
		}
		m.Gold = proto.Int32(value)
	}
}

func (m *RoleCache) SetFreeGold(value int32) {
	if m != nil {
		if m.FreeGold != nil {
			*m.FreeGold = value
			return
		}
		m.FreeGold = proto.Int32(value)
	}
}

func (m *RoleCache) SetTrophy(value int32) {
	if m != nil {
		if m.Trophy != nil {
			*m.Trophy = value
			return
		}
		m.Trophy = proto.Int32(value)
	}
}

func (m *RoleCache) SetLeagueLv(value int32) {
	if m != nil {
		if m.LeagueLv != nil {
			*m.LeagueLv = value
			return
		}
		m.LeagueLv = proto.Int32(value)
	}
}

func (m *RoleCache) SetAttackWinCount(value int32) {
	if m != nil {
		if m.AttackWinCount != nil {
			*m.AttackWinCount = value
			return
		}
		m.AttackWinCount = proto.Int32(value)
	}
}

func (m *RoleCache) SetDefenceWinCount(value int32) {
	if m != nil {
		if m.DefenceWinCount != nil {
			*m.DefenceWinCount = value
			return
		}
		m.DefenceWinCount = proto.Int32(value)
	}
}

func (m *RoleCache) SetShield(value int64) {
	if m != nil {
		if m.Shield != nil {
			*m.Shield = value
			return
		}
		m.Shield = proto.Int64(value)
	}
}

func (m *RoleCache) SetVip(value int64) {
	if m != nil {
		if m.Vip != nil {
			*m.Vip = value
			return
		}
		m.Vip = proto.Int64(value)
	}
}

func (m *RoleCache) SetChatFreeTime(value int32) {
	if m != nil {
		if m.ChatFreeTime != nil {
			*m.ChatFreeTime = value
			return
		}
		m.ChatFreeTime = proto.Int32(value)
	}
}

func (m *RoleCache) SetChatRefreshTimestamp(value int64) {
	if m != nil {
		if m.ChatRefreshTimestamp != nil {
			*m.ChatRefreshTimestamp = value
			return
		}
		m.ChatRefreshTimestamp = proto.Int64(value)
	}
}

func (m *RoleCache) SetMagicQueueType(value int32) {
	if m != nil {
		if m.MagicQueueType != nil {
			*m.MagicQueueType = value
			return
		}
		m.MagicQueueType = proto.Int32(value)
	}
}

func (m *RoleCache) SetMagicQueueId(value int64) {
	if m != nil {
		if m.MagicQueueId != nil {
			*m.MagicQueueId = value
			return
		}
		m.MagicQueueId = proto.Int64(value)
	}
}

func (m *RoleCache) SetNewPlayerGuideStep(value int32) {
	if m != nil {
		if m.NewPlayerGuideStep != nil {
			*m.NewPlayerGuideStep = value
			return
		}
		m.NewPlayerGuideStep = proto.Int32(value)
	}
}

func (m *RoleCache) SetLoginTime(value int64) {
	if m != nil {
		if m.LoginTime != nil {
			*m.LoginTime = value
			return
		}
		m.LoginTime = proto.Int64(value)
	}
}

type RoleStateCache struct {
	OnlineServer     *int32 `protobuf:"varint,1,req,name=online_server" json:"online_server,omitempty"`
	FightLock        *int64 `protobuf:"varint,2,req,name=fight_lock" json:"fight_lock,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoleStateCache) Reset()         { *m = RoleStateCache{} }
func (m *RoleStateCache) String() string { return proto.CompactTextString(m) }
func (*RoleStateCache) ProtoMessage()    {}

func (m *RoleStateCache) GetOnlineServer() int32 {
	if m != nil && m.OnlineServer != nil {
		return *m.OnlineServer
	}
	return 0
}

func (m *RoleStateCache) GetFightLock() int64 {
	if m != nil && m.FightLock != nil {
		return *m.FightLock
	}
	return 0
}

func (m *RoleStateCache) SetOnlineServer(value int32) {
	if m != nil {
		if m.OnlineServer != nil {
			*m.OnlineServer = value
			return
		}
		m.OnlineServer = proto.Int32(value)
	}
}

func (m *RoleStateCache) SetFightLock(value int64) {
	if m != nil {
		if m.FightLock != nil {
			*m.FightLock = value
			return
		}
		m.FightLock = proto.Int64(value)
	}
}

func init() {
}
